    // --- Science R2 D1 (Age 3) — 10 activities ---
    {
      id: 'science-animal-sounds-r2-d1',
      title: 'What Sound? 🐄',
      instruction: 'Match the animal to the sound it makes!',
      type: 'multipleChoice',
      difficulty: 1,
      data: [
        { question: 'What sound does a cow make? 🐄', options: ['Moo', 'Woof', 'Meow', 'Quack'], answer: 'Moo', hint: 'Cows say moooo!' },
        { question: 'What sound does a duck make? 🦆', options: ['Quack', 'Moo', 'Baa', 'Oink'], answer: 'Quack', hint: 'Ducks say quack quack!' },
        { question: 'What sound does a pig make? 🐷', options: ['Oink', 'Meow', 'Moo', 'Woof'], answer: 'Oink', hint: 'Pigs say oink oink!' },
        { question: 'What sound does a sheep make? 🐑', options: ['Baa', 'Quack', 'Moo', 'Roar'], answer: 'Baa', hint: 'Sheep say baaaa!' },
        { question: 'What sound does a rooster make? 🐓', options: ['Cock-a-doodle-doo', 'Woof', 'Meow', 'Hiss'], answer: 'Cock-a-doodle-doo', hint: 'Roosters wake everyone up in the morning!' },
        { question: 'What sound does a lion make? 🦁', options: ['Roar', 'Quack', 'Moo', 'Baa'], answer: 'Roar', hint: 'Lions are loud and powerful!' },
        { question: 'What sound does a cat make? 🐱', options: ['Meow', 'Woof', 'Oink', 'Moo'], answer: 'Meow', hint: 'Cats say meow and purr!' },
        { question: 'What sound does a dog make? 🐶', options: ['Woof', 'Meow', 'Quack', 'Baa'], answer: 'Woof', hint: 'Dogs bark and say woof!' },
      ],
    },
    {
      id: 'science-body-senses-r2-d1',
      title: 'My Five Senses 👀',
      instruction: 'Which sense do you use?',
      type: 'multipleChoice',
      difficulty: 1,
      data: [
        { question: 'You use your eyes to... 👀', options: ['See', 'Hear', 'Smell', 'Taste'], answer: 'See', hint: 'Your eyes help you look at things!' },
        { question: 'You use your ears to... 👂', options: ['Hear', 'See', 'Touch', 'Smell'], answer: 'Hear', hint: 'Your ears catch sounds around you!' },
        { question: 'You use your nose to... 👃', options: ['Smell', 'See', 'Taste', 'Hear'], answer: 'Smell', hint: 'Your nose sniffs flowers and food!' },
        { question: 'You use your tongue to... 👅', options: ['Taste', 'Smell', 'See', 'Hear'], answer: 'Taste', hint: 'Your tongue tells you if food is sweet or sour!' },
        { question: 'You use your hands to... 🖐️', options: ['Touch', 'Hear', 'Smell', 'Taste'], answer: 'Touch', hint: 'Your hands feel if things are soft or rough!' },
        { question: 'Which sense helps you enjoy music? 🎵', options: ['Hearing', 'Sight', 'Touch', 'Taste'], answer: 'Hearing', hint: 'You listen to music with your ears!' },
        { question: 'Which sense tells you a cookie is yummy? 🍪', options: ['Taste', 'Sight', 'Hearing', 'Touch'], answer: 'Taste', hint: 'Your mouth tells you how food tastes!' },
        { question: 'Which sense helps you see a rainbow? 🌈', options: ['Sight', 'Taste', 'Touch', 'Smell'], answer: 'Sight', hint: 'You see colors with your eyes!' },
      ],
    },
    {
      id: 'science-weather-wear-r2-d1',
      title: 'Weather Clothes 🧥',
      instruction: 'What should you wear in this weather?',
      type: 'multipleChoice',
      difficulty: 1,
      data: [
        { question: 'It is snowing! What should you wear? ❄️', options: ['Warm coat and boots', 'Swimsuit', 'T-shirt and shorts', 'Nothing extra'], answer: 'Warm coat and boots', hint: 'Snow is cold — bundle up!' },
        { question: 'It is sunny and hot! What should you wear? ☀️', options: ['Shorts and sunscreen', 'Winter coat', 'Scarf and mittens', 'Rain boots'], answer: 'Shorts and sunscreen', hint: 'Keep cool in the sun!' },
        { question: 'It is raining! What do you need? 🌧️', options: ['Umbrella and rain boots', 'Sunglasses', 'Swimsuit', 'Winter hat'], answer: 'Umbrella and rain boots', hint: 'Stay dry in the rain!' },
        { question: 'It is windy! What might blow away? 🌬️', options: ['Your hat', 'Your shoes', 'Your backpack', 'Your house'], answer: 'Your hat', hint: 'Light things can blow away in wind!' },
        { question: 'What keeps your hands warm in winter? 🧤', options: ['Gloves or mittens', 'Sandals', 'Sunglasses', 'Shorts'], answer: 'Gloves or mittens', hint: 'They cover each finger to keep them toasty!' },
        { question: 'What protects your eyes from the sun? 😎', options: ['Sunglasses', 'Earmuffs', 'Rain boots', 'Scarf'], answer: 'Sunglasses', hint: 'They have dark lenses!' },
        { question: 'What do you wear on your feet when it rains? 🥾', options: ['Rain boots', 'Flip flops', 'Slippers', 'No shoes'], answer: 'Rain boots', hint: 'Waterproof boots keep feet dry!' },
        { question: 'What keeps you warm around your neck? 🧣', options: ['A scarf', 'A belt', 'A bracelet', 'A headband'], answer: 'A scarf', hint: 'You wrap it around your neck!' },
      ],
    },
    {
      id: 'science-plant-basics-r2-d1',
      title: 'Plants Are Amazing! 🌱',
      instruction: 'Learn about plants!',
      type: 'flashcard',
      difficulty: 1,
      data: [
        { front: '🌱 Seed', back: 'A tiny package that a new plant grows from!' },
        { front: '🌿 Stem', back: 'The part that holds the plant up tall!' },
        { front: '🍃 Leaf', back: 'The green part that catches sunlight!' },
        { front: '🌸 Flower', back: 'The colorful part that makes seeds!' },
        { front: '🌳 Roots', back: 'Hidden underground — they drink up water!' },
        { front: '💧 Water', back: 'Plants need water to drink and grow!' },
        { front: '☀️ Sunlight', back: 'Plants need sunshine to make their food!' },
        { front: '🪴 Soil', back: 'Dirt where plants put their roots!' },
      ],
    },
    {
      id: 'science-colors-mixing-r2-d1',
      title: 'Mixing Colors! 🎨',
      instruction: 'What color do you get when you mix these?',
      type: 'multipleChoice',
      difficulty: 1,
      data: [
        { question: 'Red + Yellow = ? 🔴🟡', options: ['Orange', 'Green', 'Purple', 'Blue'], answer: 'Orange', hint: 'Think of a sunset or a carrot!' },
        { question: 'Blue + Yellow = ? 🔵🟡', options: ['Green', 'Orange', 'Purple', 'Red'], answer: 'Green', hint: 'Think of grass and leaves!' },
        { question: 'Red + Blue = ? 🔴🔵', options: ['Purple', 'Green', 'Orange', 'Yellow'], answer: 'Purple', hint: 'Think of grapes!' },
        { question: 'Red + White = ? 🔴⚪', options: ['Pink', 'Orange', 'Gray', 'Yellow'], answer: 'Pink', hint: 'A lighter, softer red!' },
        { question: 'Black + White = ? ⚫⚪', options: ['Gray', 'Brown', 'Purple', 'Blue'], answer: 'Gray', hint: 'Like a rain cloud!' },
        { question: 'Which colors are PRIMARY colors? 🎨', options: ['Red, Blue, Yellow', 'Green, Orange, Purple', 'Pink, Gray, Brown', 'Black, White, Red'], answer: 'Red, Blue, Yellow', hint: 'You cannot make these by mixing other colors!' },
        { question: 'Orange, Green, and Purple are called... 🌈', options: ['Secondary colors', 'Primary colors', 'Dark colors', 'Light colors'], answer: 'Secondary colors', hint: 'You make them by mixing two primary colors!' },
        { question: 'What two colors make green? 💚', options: ['Blue and Yellow', 'Red and Blue', 'Red and Yellow', 'Black and White'], answer: 'Blue and Yellow', hint: 'One is the color of the sky, one is the color of the sun!' },
      ],
    },
    {
      id: 'science-pet-care-r2-d1',
      title: 'Taking Care of Pets 🐾',
      instruction: 'What do pets need?',
      type: 'multipleChoice',
      difficulty: 1,
      data: [
        { question: 'What does a pet dog need every day? 🐕', options: ['Food and water', 'A TV', 'A phone', 'Money'], answer: 'Food and water', hint: 'Dogs get hungry and thirsty just like you!' },
        { question: 'Where does a pet fish live? 🐠', options: ['In a fish tank with water', 'In a cage', 'On a leash', 'In a bed'], answer: 'In a fish tank with water', hint: 'Fish need water to breathe!' },
        { question: 'What does a pet cat like to do? 🐱', options: ['Nap and play', 'Swim in a pool', 'Fly in the sky', 'Drive a car'], answer: 'Nap and play', hint: 'Cats love cozy spots and chasing toys!' },
        { question: 'Why do dogs need walks? 🦮', options: ['To get exercise and explore', 'To go shopping', 'To visit school', 'To drive around'], answer: 'To get exercise and explore', hint: 'Walking keeps dogs healthy and happy!' },
        { question: 'What does a hamster sleep in? 🐹', options: ['A cozy nest of bedding', 'A swimming pool', 'A birdhouse', 'A shoe'], answer: 'A cozy nest of bedding', hint: 'Hamsters make soft little beds to sleep in!' },
        { question: 'What do pets need from their owners? ❤️', options: ['Love and care', 'Video games', 'Homework', 'Candy'], answer: 'Love and care', hint: 'Pets are happiest when their people love them!' },
        { question: 'How do you keep a pet healthy? 🏥', options: ['Visit the vet for checkups', 'Give them candy', 'Let them watch TV', 'Do nothing'], answer: 'Visit the vet for checkups', hint: 'The vet is a doctor for animals!' },
        { question: 'A pet bird lives in a... 🐦', options: ['Cage', 'Fish tank', 'Dog house', 'Barn'], answer: 'Cage', hint: 'It has bars and a little door!' },
      ],
    },
    {
      id: 'science-earth-sky-r2-d1',
      title: 'Earth and Sky 🌍',
      instruction: 'What do you see in the sky and on Earth?',
      type: 'flashcard',
      difficulty: 1,
      data: [
        { front: '☀️ Sun', back: 'A huge star that gives us light and warmth!' },
        { front: '🌙 Moon', back: 'It shines at night and changes shape!' },
        { front: '⭐ Stars', back: 'Tiny lights in the night sky — they are far-away suns!' },
        { front: '☁️ Clouds', back: 'Fluffy white puffs made of tiny water drops!' },
        { front: '🌈 Rainbow', back: 'Colorful arc that appears after rain when the sun shines!' },
        { front: '🌍 Earth', back: 'Our planet — home to people, animals, and plants!' },
        { front: '⛰️ Mountains', back: 'Very tall landforms that reach up to the sky!' },
        { front: '🌊 Oceans', back: 'Huge bodies of salty water covering most of Earth!' },
      ],
    },
    {
      id: 'science-food-groups-r2-d1',
      title: 'Healthy Food Groups 🥦',
      instruction: 'Which food group does this belong to?',
      type: 'multipleChoice',
      difficulty: 1,
      data: [
        { question: 'An apple is a... 🍎', options: ['Fruit', 'Vegetable', 'Grain', 'Dairy'], answer: 'Fruit', hint: 'Apples grow on trees and are sweet!' },
        { question: 'Broccoli is a... 🥦', options: ['Vegetable', 'Fruit', 'Meat', 'Dairy'], answer: 'Vegetable', hint: 'Green veggies are so good for you!' },
        { question: 'Milk comes from... 🥛', options: ['Cows', 'Trees', 'The ocean', 'Rocks'], answer: 'Cows', hint: 'Moo! Dairy cows give us milk!' },
        { question: 'Bread is made from... 🍞', options: ['Grain (wheat)', 'Meat', 'Fruit', 'Vegetables'], answer: 'Grain (wheat)', hint: 'Wheat is ground into flour for bread!' },
        { question: 'Chicken is a type of... 🍗', options: ['Protein/Meat', 'Fruit', 'Grain', 'Dairy'], answer: 'Protein/Meat', hint: 'Meat gives us protein to grow strong!' },
        { question: 'Which is a healthy snack? 🥕', options: ['Carrots and hummus', 'Candy bars', 'Soda', 'Chips only'], answer: 'Carrots and hummus', hint: 'Vegetables are a great healthy snack!' },
        { question: 'Cheese is a... 🧀', options: ['Dairy food', 'Fruit', 'Vegetable', 'Grain'], answer: 'Dairy food', hint: 'Cheese is made from milk!' },
        { question: 'Why should we eat fruits and vegetables? 🍇', options: ['They give us vitamins to stay healthy', 'They taste bad', 'We do not need them', 'Only grown-ups eat them'], answer: 'They give us vitamins to stay healthy', hint: 'Vitamins help our bodies work well!' },
      ],
    },
    {
      id: 'science-bugs-insects-r2-d1',
      title: 'Bugs and Insects 🐛',
      instruction: 'Learn about tiny creatures!',
      type: 'flashcard',
      difficulty: 1,
      data: [
        { front: '🐛 Caterpillar', back: 'A fuzzy worm that turns into a butterfly!' },
        { front: '🐞 Ladybug', back: 'A red beetle with black dots — they eat garden pests!' },
        { front: '🐜 Ant', back: 'Tiny but super strong — they work together in teams!' },
        { front: '🐝 Bee', back: 'Makes honey and helps flowers grow by spreading pollen!' },
        { front: '🦗 Grasshopper', back: 'Has big back legs and can jump really far!' },
        { front: '🪲 Beetle', back: 'Has a hard shell on its back for protection!' },
        { front: '🦟 Mosquito', back: 'A tiny flying insect that buzzes and bites!' },
        { front: '🕷️ Spider', back: 'Has 8 legs and spins webs to catch food — not an insect!' },
      ],
    },
    {
      id: 'science-water-land-air-r2-d1',
      title: 'Water, Land, or Air? 🌊',
      instruction: 'Where does this animal live?',
      type: 'dragDrop',
      difficulty: 1,
      data: {
        items: [
          { id: 1, text: '🐠 Fish' },
          { id: 2, text: '🐦 Eagle' },
          { id: 3, text: '🐻 Bear' },
          { id: 4, text: '🐬 Dolphin' },
          { id: 5, text: '🦅 Hawk' },
          { id: 6, text: '🐇 Rabbit' },
          { id: 7, text: '🐙 Octopus' },
          { id: 8, text: '🦎 Lizard' },
        ],
        targets: [
          { id: 1, text: '🌊 Water' },
          { id: 2, text: '🌤️ Air' },
          { id: 3, text: '🏔️ Land' },
          { id: 4, text: '🌊 Water' },
          { id: 5, text: '🌤️ Air' },
          { id: 6, text: '🏔️ Land' },
          { id: 7, text: '🌊 Water' },
          { id: 8, text: '🏔️ Land' },
        ],
      },
    },
    // --- Science R2 D2 (Age 4) — 10 activities ---
    {
      id: 'science-animal-diets-r2-d2',
      title: 'What Do Animals Eat? 🍖',
      instruction: 'Match the animal to its food!',
      type: 'multipleChoice',
      difficulty: 2,
      data: [
        { question: 'What does a rabbit eat? 🐰', options: ['Carrots and vegetables', 'Fish', 'Meat', 'Rocks'], answer: 'Carrots and vegetables', hint: 'Rabbits love crunchy veggies!' },
        { question: 'What does a lion eat? 🦁', options: ['Meat from other animals', 'Grass', 'Fruits', 'Flowers'], answer: 'Meat from other animals', hint: 'Lions are predators that hunt!' },
        { question: 'What does a cow eat? 🐄', options: ['Grass and hay', 'Fish', 'Meat', 'Bugs'], answer: 'Grass and hay', hint: 'Cows munch on green grass in fields!' },
        { question: 'Animals that eat only plants are called... 🌿', options: ['Herbivores', 'Carnivores', 'Omnivores', 'Insectivores'], answer: 'Herbivores', hint: 'Herb means plant!' },
        { question: 'Animals that eat only meat are called... 🥩', options: ['Carnivores', 'Herbivores', 'Omnivores', 'Vegetarians'], answer: 'Carnivores', hint: 'Carni means meat!' },
        { question: 'Animals that eat both plants and meat are called... 🍖🥬', options: ['Omnivores', 'Herbivores', 'Carnivores', 'None of these'], answer: 'Omnivores', hint: 'Omni means all — they eat everything!' },
        { question: 'A bear eats berries AND fish. It is an... 🐻', options: ['Omnivore', 'Herbivore', 'Carnivore', 'Insectivore'], answer: 'Omnivore', hint: 'It eats plants AND meat!' },
        { question: 'A horse eats grass and oats. It is a... 🐴', options: ['Herbivore', 'Carnivore', 'Omnivore', 'Insectivore'], answer: 'Herbivore', hint: 'It only eats plants!' },
      ],
    },
    {
      id: 'science-habitats-r2-d2',
      title: 'Animal Habitats 🏜️',
      instruction: 'Where does this animal live?',
      type: 'dragDrop',
      difficulty: 2,
      data: {
        items: [
          { id: 1, text: '🐫 Camel' },
          { id: 2, text: '🐧 Penguin' },
          { id: 3, text: '🐵 Monkey' },
          { id: 4, text: '🐊 Crocodile' },
          { id: 5, text: '🦂 Scorpion' },
          { id: 6, text: '🐻‍❄️ Polar Bear' },
          { id: 7, text: '🦜 Parrot' },
          { id: 8, text: '🐊 Alligator' },
        ],
        targets: [
          { id: 1, text: '🏜️ Desert' },
          { id: 2, text: '🧊 Arctic/Antarctic' },
          { id: 3, text: '🌴 Rainforest' },
          { id: 4, text: '🌿 Swamp/Wetland' },
          { id: 5, text: '🏜️ Desert' },
          { id: 6, text: '🧊 Arctic/Antarctic' },
          { id: 7, text: '🌴 Rainforest' },
          { id: 8, text: '🌿 Swamp/Wetland' },
        ],
      },
    },
    {
      id: 'science-rocks-minerals-r2-d2',
      title: 'Rocks and Minerals 🪨',
      instruction: 'Learn about rocks!',
      type: 'flashcard',
      difficulty: 2,
      data: [
        { front: '🪨 Rock', back: 'Rocks are solid pieces of Earth made from minerals!' },
        { front: '🔥 Igneous Rock', back: 'Made from cooled lava or magma — like from a volcano!' },
        { front: '🏖️ Sedimentary Rock', back: 'Made from layers of sand and mud pressed together over time!' },
        { front: '💎 Metamorphic Rock', back: 'Changed by heat and pressure deep underground!' },
        { front: '💎 Diamond', back: 'The hardest mineral on Earth — super sparkly!' },
        { front: '🧂 Quartz', back: 'A very common mineral found in many rocks!' },
        { front: '�ite Fossil', back: 'Bones or prints of ancient animals preserved in rock!' },
        { front: '🌋 Lava Rock', back: 'Light and full of holes — formed from bubbly lava!' },
      ],
    },
    {
      id: 'science-life-cycles-r2-d2',
      title: 'Animal Life Cycles 🐣',
      instruction: 'Put the life cycle in order!',
      type: 'multipleChoice',
      difficulty: 2,
      data: [
        { question: 'What comes first in a chicken life cycle? 🐔', options: ['Egg', 'Chick', 'Hen', 'Rooster'], answer: 'Egg', hint: 'Everything starts inside a shell!' },
        { question: 'A caterpillar turns into a... 🦋', options: ['Butterfly', 'Ladybug', 'Ant', 'Spider'], answer: 'Butterfly', hint: 'A beautiful flying insect with colorful wings!' },
        { question: 'A tadpole grows up to be a... 🐸', options: ['Frog', 'Fish', 'Snake', 'Turtle'], answer: 'Frog', hint: 'It starts in water then hops on land!' },
        { question: 'What does a caterpillar make before becoming a butterfly? 🫘', options: ['A chrysalis (cocoon)', 'A nest', 'A web', 'A hole'], answer: 'A chrysalis (cocoon)', hint: 'It wraps itself up to transform inside!' },
        { question: 'Baby frogs that live in water are called... 🐸', options: ['Tadpoles', 'Kittens', 'Puppies', 'Chicks'], answer: 'Tadpoles', hint: 'They have tails and swim like fish!' },
        { question: 'What hatches from a bird egg? 🥚', options: ['A baby chick', 'A fish', 'A puppy', 'A snake'], answer: 'A baby chick', hint: 'Baby birds come from eggs!' },
        { question: 'A puppy grows up to be a... 🐕', options: ['Dog', 'Cat', 'Horse', 'Bear'], answer: 'Dog', hint: 'Puppies are baby dogs!' },
        { question: 'A kitten grows up to be a... 🐈', options: ['Cat', 'Dog', 'Lion', 'Tiger'], answer: 'Cat', hint: 'Kittens are baby cats!' },
      ],
    },
    {
      id: 'science-magnets-r2-d2',
      title: 'Magnets Are Magical! 🧲',
      instruction: 'What do magnets do?',
      type: 'multipleChoice',
      difficulty: 2,
      data: [
        { question: 'What do magnets attract? 🧲', options: ['Metal things like iron', 'Wood', 'Plastic', 'Paper'], answer: 'Metal things like iron', hint: 'Magnets stick to certain metals!' },
        { question: 'Will a magnet stick to a wooden table? 🪵', options: ['No', 'Yes', 'Maybe', 'Only at night'], answer: 'No', hint: 'Magnets only attract certain metals!' },
        { question: 'Will a magnet stick to a refrigerator? 🧊', options: ['Yes', 'No', 'Maybe', 'Only sometimes'], answer: 'Yes', hint: 'Refrigerators are made of metal!' },
        { question: 'Every magnet has how many poles? 🧲', options: ['Two — North and South', 'One', 'Three', 'None'], answer: 'Two — North and South', hint: 'Like the top and bottom of Earth!' },
        { question: 'What happens when two North poles meet? 🧲🧲', options: ['They push apart (repel)', 'They stick together', 'Nothing happens', 'They break'], answer: 'They push apart (repel)', hint: 'Same poles do not like each other!' },
        { question: 'What happens when North meets South? 🧲', options: ['They pull together (attract)', 'They push apart', 'Nothing', 'They break'], answer: 'They pull together (attract)', hint: 'Opposite poles are attracted to each other!' },
        { question: 'Which item would a magnet pick up? 🧲', options: ['A paper clip', 'A leaf', 'A rubber ball', 'A cotton sock'], answer: 'A paper clip', hint: 'Paper clips are made of metal!' },
        { question: 'Where do we use magnets at home? 🏠', options: ['On the refrigerator door', 'In the bathtub', 'On the carpet', 'In food'], answer: 'On the refrigerator door', hint: 'Fridge magnets hold up pictures and notes!' },
      ],
    },
    {
      id: 'science-weather-types-r2-d2',
      title: 'Types of Weather ⛈️',
      instruction: 'Learn about different kinds of weather!',
      type: 'flashcard',
      difficulty: 2,
      data: [
        { front: '⛈️ Thunderstorm', back: 'A storm with rain, lightning, and loud thunder!' },
        { front: '🌪️ Tornado', back: 'A spinning funnel of wind that is very dangerous!' },
        { front: '🌫️ Fog', back: 'A cloud that sits on the ground — hard to see through!' },
        { front: '🌨️ Blizzard', back: 'A big snowstorm with strong winds!' },
        { front: '☀️ Sunny', back: 'Clear skies with bright sunshine — great for playing outside!' },
        { front: '🌦️ Partly Cloudy', back: 'Some clouds and some sunshine mixed together!' },
        { front: '🌧️ Drizzle', back: 'Very light, gentle rain — like a mist!' },
        { front: '❄️ Hail', back: 'Balls of ice that fall from storm clouds!' },
      ],
    },
    {
      id: 'science-seasons-changes-r2-d2',
      title: 'What Happens Each Season? 🍂',
      instruction: 'Match the event to the right season!',
      type: 'dragDrop',
      difficulty: 2,
      data: {
        items: [
          { id: 1, text: '🍂 Leaves change color' },
          { id: 2, text: '⛄ Building snowmen' },
          { id: 3, text: '🌸 Flowers bloom' },
          { id: 4, text: '🏊 Swimming at the pool' },
          { id: 5, text: '🎃 Pumpkin picking' },
          { id: 6, text: '🧤 Wearing mittens' },
          { id: 7, text: '🐣 Baby animals born' },
          { id: 8, text: '🍦 Eating ice cream outside' },
        ],
        targets: [
          { id: 1, text: '🍂 Fall' },
          { id: 2, text: '❄️ Winter' },
          { id: 3, text: '🌸 Spring' },
          { id: 4, text: '☀️ Summer' },
          { id: 5, text: '🍂 Fall' },
          { id: 6, text: '❄️ Winter' },
          { id: 7, text: '🌸 Spring' },
          { id: 8, text: '☀️ Summer' },
        ],
      },
    },
    {
      id: 'science-dinosaur-types-r2-d2',
      title: 'Dinosaur World 🦕',
      instruction: 'Learn about different dinosaurs!',
      type: 'multipleChoice',
      difficulty: 2,
      data: [
        { question: 'Which dinosaur had a very long neck? 🦕', options: ['Brachiosaurus', 'T-Rex', 'Stegosaurus', 'Triceratops'], answer: 'Brachiosaurus', hint: 'It needed a long neck to reach tall trees!' },
        { question: 'Which dinosaur had three horns on its head? 🦖', options: ['Triceratops', 'T-Rex', 'Velociraptor', 'Pterodactyl'], answer: 'Triceratops', hint: 'Tri means three — three horns!' },
        { question: 'Which dinosaur had tiny arms and big teeth? 🦖', options: ['T-Rex', 'Brachiosaurus', 'Stegosaurus', 'Diplodocus'], answer: 'T-Rex', hint: 'The king of the dinosaurs!' },
        { question: 'Which dinosaur had plates on its back? 🦕', options: ['Stegosaurus', 'T-Rex', 'Triceratops', 'Velociraptor'], answer: 'Stegosaurus', hint: 'Big flat plates along its spine and spikes on its tail!' },
        { question: 'Pterodactyl could do what special thing? 🦅', options: ['Fly', 'Swim', 'Dig', 'Climb trees'], answer: 'Fly', hint: 'It had wings made of skin!' },
        { question: 'What do we call a scientist who studies dinosaurs? 🔬', options: ['Paleontologist', 'Astronaut', 'Chef', 'Teacher'], answer: 'Paleontologist', hint: 'They dig up dinosaur bones and fossils!' },
        { question: 'Are dinosaurs still alive today? 🤔', options: ['No, they went extinct long ago', 'Yes, they live in the ocean', 'Yes, they hide in caves', 'Yes, at the zoo'], answer: 'No, they went extinct long ago', hint: 'Dinosaurs disappeared millions of years ago!' },
        { question: 'What do paleontologists find in rocks? 🦴', options: ['Fossils — old bones and prints', 'Living dinosaurs', 'Gold coins', 'Dinosaur eggs with babies'], answer: 'Fossils — old bones and prints', hint: 'Fossils are preserved remains from long ago!' },
      ],
    },
    {
      id: 'science-ocean-zones-r2-d2',
      title: 'Ocean Layers 🌊',
      instruction: 'Learn about the ocean from top to bottom!',
      type: 'flashcard',
      difficulty: 2,
      data: [
        { front: '🏄 Sunlight Zone', back: 'The top of the ocean where light reaches — most sea creatures live here!' },
        { front: '🐋 Twilight Zone', back: 'Dim and darker — some whales and jellyfish swim here!' },
        { front: '🦑 Midnight Zone', back: 'Completely dark — strange glowing animals live here!' },
        { front: '🌡️ Temperature', back: 'The ocean gets colder as you go deeper!' },
        { front: '🪸 Coral Reef', back: 'Colorful underwater gardens where thousands of fish live!' },
        { front: '🐚 Tide Pools', back: 'Little pools at the beach full of crabs, snails, and starfish!' },
        { front: '🧊 Icebergs', back: 'Huge chunks of floating ice — most of it is underwater!' },
        { front: '🐠 Plankton', back: 'Tiny floating creatures — food for whales and many fish!' },
      ],
    },
    {
      id: 'science-energy-sources-r2-d2',
      title: 'What Makes Energy? ⚡',
      instruction: 'Where does energy come from?',
      type: 'multipleChoice',
      difficulty: 2,
      data: [
        { question: 'The sun gives us... ☀️', options: ['Light and heat energy', 'Food', 'Water', 'Air'], answer: 'Light and heat energy', hint: 'The sun warms the Earth and lights up the day!' },
        { question: 'What kind of energy makes things move? 🏃', options: ['Kinetic energy (movement energy)', 'Sound energy', 'Light energy', 'Heat energy'], answer: 'Kinetic energy (movement energy)', hint: 'Kinetic means moving!' },
        { question: 'Batteries store what kind of energy? 🔋', options: ['Electrical energy', 'Sound energy', 'Wind energy', 'Water energy'], answer: 'Electrical energy', hint: 'Batteries power flashlights and toys!' },
        { question: 'What energy does food give us? 🍎', options: ['Energy to move and think', 'Energy to fly', 'No energy', 'Energy to glow'], answer: 'Energy to move and think', hint: 'Food is fuel for our bodies!' },
        { question: 'Wind turbines use what to make electricity? 💨', options: ['Wind', 'Water', 'Fire', 'Rocks'], answer: 'Wind', hint: 'Big spinning blades catch the breeze!' },
        { question: 'Solar panels use what to make electricity? ☀️', options: ['Sunlight', 'Moonlight', 'Wind', 'Rain'], answer: 'Sunlight', hint: 'Solar means related to the sun!' },
        { question: 'What makes a campfire hot? 🔥', options: ['Heat energy from burning wood', 'Sound energy', 'Light energy only', 'Cold energy'], answer: 'Heat energy from burning wood', hint: 'Fire gives off heat and light!' },
        { question: 'A guitar makes what kind of energy? 🎸', options: ['Sound energy', 'Heat energy', 'Light energy', 'Electrical energy'], answer: 'Sound energy', hint: 'Strumming strings makes vibrations you can hear!' },
      ],
    },
    // --- Science R2 D3 (Age 5) — 10 activities ---
    {
      id: 'science-solar-system-r2-d3',
      title: 'Our Solar System 🪐',
      instruction: 'Learn about the planets!',
      type: 'multipleChoice',
      difficulty: 3,
      data: [
        { question: 'Which planet is closest to the Sun? ☀️', options: ['Mercury', 'Venus', 'Earth', 'Mars'], answer: 'Mercury', hint: 'The smallest planet, right next to the Sun!' },
        { question: 'Which planet do we live on? 🌍', options: ['Earth', 'Mars', 'Venus', 'Jupiter'], answer: 'Earth', hint: 'The blue planet with water and life!' },
        { question: 'Which planet is known as the Red Planet? 🔴', options: ['Mars', 'Jupiter', 'Saturn', 'Mercury'], answer: 'Mars', hint: 'Its rusty soil makes it look red!' },
        { question: 'Which planet has beautiful rings? 💍', options: ['Saturn', 'Earth', 'Mars', 'Venus'], answer: 'Saturn', hint: 'The rings are made of ice and rock!' },
        { question: 'Which planet is the biggest? 🪐', options: ['Jupiter', 'Saturn', 'Earth', 'Neptune'], answer: 'Jupiter', hint: 'This giant planet has a Great Red Spot!' },
        { question: 'How many planets are in our solar system? 🔢', options: ['8', '6', '10', '12'], answer: '8', hint: 'Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune!' },
        { question: 'What is at the center of our solar system? ☀️', options: ['The Sun', 'The Moon', 'Earth', 'Jupiter'], answer: 'The Sun', hint: 'All planets orbit around this star!' },
        { question: 'The Moon orbits around... 🌙', options: ['Earth', 'The Sun', 'Mars', 'Jupiter'], answer: 'Earth', hint: 'We can see the Moon from our planet!' },
      ],
    },
    {
      id: 'science-human-body-r2-d3',
      title: 'Inside Your Body 🫀',
      instruction: 'Learn about the amazing human body!',
      type: 'multipleChoice',
      difficulty: 3,
      data: [
        { question: 'What organ pumps blood through your body? 🫀', options: ['Heart', 'Brain', 'Lungs', 'Stomach'], answer: 'Heart', hint: 'You can feel it beating in your chest!' },
        { question: 'What organ helps you think and learn? 🧠', options: ['Brain', 'Heart', 'Stomach', 'Lungs'], answer: 'Brain', hint: 'It is inside your head and controls everything!' },
        { question: 'What do lungs help you do? 🫁', options: ['Breathe', 'Eat', 'See', 'Walk'], answer: 'Breathe', hint: 'They fill with air when you inhale!' },
        { question: 'What breaks down the food you eat? 🍽️', options: ['Stomach', 'Brain', 'Heart', 'Lungs'], answer: 'Stomach', hint: 'Food goes there after you swallow!' },
        { question: 'Bones help your body by... 🦴', options: ['Giving it shape and support', 'Digesting food', 'Pumping blood', 'Breathing air'], answer: 'Giving it shape and support', hint: 'Without bones, you would be like jelly!' },
        { question: 'Muscles help you... 💪', options: ['Move your body', 'Think thoughts', 'Breathe air', 'Hear sounds'], answer: 'Move your body', hint: 'Flex your arm — that is a muscle working!' },
        { question: 'What carries blood around your body? 🩸', options: ['Blood vessels (veins and arteries)', 'Bones', 'Muscles', 'Skin'], answer: 'Blood vessels (veins and arteries)', hint: 'Like tiny tubes running through your whole body!' },
        { question: 'Skin protects your body from... 🛡️', options: ['Germs and the sun', 'Nothing', 'Only water', 'Only cold'], answer: 'Germs and the sun', hint: 'Your skin is your body\'s biggest organ!' },
      ],
    },
    {
      id: 'science-food-chain-r2-d3',
      title: 'Food Chains 🔗',
      instruction: 'Who eats whom in nature?',
      type: 'multipleChoice',
      difficulty: 3,
      data: [
        { question: 'In a food chain, plants are called... 🌱', options: ['Producers', 'Consumers', 'Decomposers', 'Predators'], answer: 'Producers', hint: 'Plants produce (make) their own food from sunlight!' },
        { question: 'Animals that eat plants are called... 🐰', options: ['Herbivores (primary consumers)', 'Producers', 'Decomposers', 'Apex predators'], answer: 'Herbivores (primary consumers)', hint: 'They are the first to consume (eat) the producers!' },
        { question: 'A fox eats a rabbit. The fox is a... 🦊', options: ['Predator', 'Producer', 'Herbivore', 'Plant'], answer: 'Predator', hint: 'Predators hunt and eat other animals!' },
        { question: 'What is at the bottom of most food chains? 🌿', options: ['Plants', 'Lions', 'Eagles', 'Sharks'], answer: 'Plants', hint: 'Plants start the chain by making energy from sunlight!' },
        { question: 'Grass → Rabbit → Fox. What does the arrow mean? ➡️', options: ['Is eaten by', 'Likes', 'Lives near', 'Plays with'], answer: 'Is eaten by', hint: 'The arrow shows the flow of energy!' },
        { question: 'Mushrooms and worms that break down dead things are... 🍄', options: ['Decomposers', 'Producers', 'Predators', 'Herbivores'], answer: 'Decomposers', hint: 'They decompose — break down — dead matter!' },
        { question: 'Sun → Grass → Cow → Human is an example of a... 🔗', options: ['Food chain', 'Life cycle', 'Water cycle', 'Song'], answer: 'Food chain', hint: 'Each link eats the one before it!' },
        { question: 'If all the rabbits disappeared, what happens to the foxes? 🦊', options: ['They would have less food', 'Nothing', 'They would grow bigger', 'They would eat rocks'], answer: 'They would have less food', hint: 'Food chains are connected — changes affect everyone!' },
      ],
    },
    {
      id: 'science-simple-machines-r2-d3',
      title: 'Simple Machines 🔧',
      instruction: 'Learn about machines that make work easier!',
      type: 'flashcard',
      difficulty: 3,
      data: [
        { front: '📐 Inclined Plane', back: 'A ramp! It makes it easier to move things up — like a wheelchair ramp!' },
        { front: '🔩 Screw', back: 'A twisted inclined plane — it holds things together tightly!' },
        { front: '⚙️ Wheel and Axle', back: 'A wheel on a rod — makes moving heavy things easier, like a wagon!' },
        { front: '🎣 Pulley', back: 'A wheel with a rope — helps lift heavy things up, like a flag on a pole!' },
        { front: '⚖️ Lever', back: 'A bar on a pivot point — like a seesaw or a bottle opener!' },
        { front: '🪓 Wedge', back: 'A shape that pushes things apart — like a doorstop or an axe!' },
        { front: '🛝 Slide', back: 'A playground slide is an inclined plane — gravity pulls you down!' },
        { front: '🚲 Bicycle', back: 'Uses wheels, axles, levers, and gears — many simple machines together!' },
      ],
    },
    {
      id: 'science-earth-materials-r2-d3',
      title: 'Earth Materials 🌏',
      instruction: 'What is Earth made of?',
      type: 'multipleChoice',
      difficulty: 3,
      data: [
        { question: 'What are the three layers of Earth? 🌍', options: ['Crust, mantle, core', 'Top, middle, bottom', 'Sand, water, air', 'Rocks, trees, dirt'], answer: 'Crust, mantle, core', hint: 'Like an egg — shell, white, and yolk!' },
        { question: 'The thin outer layer we live on is the... 🏔️', options: ['Crust', 'Core', 'Mantle', 'Atmosphere'], answer: 'Crust', hint: 'Like the crust of bread — the outside layer!' },
        { question: 'What is in the very center of Earth? 🔥', options: ['A hot core made of iron', 'Water', 'Air', 'Ice'], answer: 'A hot core made of iron', hint: 'The center is extremely hot!' },
        { question: 'Soil is made from... 🪴', options: ['Tiny bits of broken rock, dead plants, and water', 'Only sand', 'Only clay', 'Only rocks'], answer: 'Tiny bits of broken rock, dead plants, and water', hint: 'Soil is a mix of many things!' },
        { question: 'What kind of rock forms from a volcano? 🌋', options: ['Igneous rock', 'Sedimentary rock', 'Metamorphic rock', 'Sandstone'], answer: 'Igneous rock', hint: 'Ignis means fire in Latin!' },
        { question: 'Erosion is when... 🌊', options: ['Wind and water wear away rock and soil', 'Rocks grow bigger', 'Mountains appear instantly', 'Nothing changes'], answer: 'Wind and water wear away rock and soil', hint: 'Water and wind slowly move earth materials!' },
        { question: 'Fossils are found in which type of rock? 🦴', options: ['Sedimentary', 'Igneous', 'Metamorphic', 'All types equally'], answer: 'Sedimentary', hint: 'Layers of sediment preserve bones and prints!' },
        { question: 'What causes earthquakes? 🏚️', options: ['Tectonic plates shifting underground', 'Wind', 'Rain', 'The moon'], answer: 'Tectonic plates shifting underground', hint: 'Giant rock plates move and bump into each other!' },
      ],
    },
    {
      id: 'science-states-matter-r2-d3',
      title: 'Solids, Liquids, Gases 🧊',
      instruction: 'What state of matter is this?',
      type: 'dragDrop',
      difficulty: 3,
      data: {
        items: [
          { id: 1, text: '🧊 Ice cube' },
          { id: 2, text: '💧 Water' },
          { id: 3, text: '💨 Steam' },
          { id: 4, text: '🪨 Rock' },
          { id: 5, text: '🥛 Milk' },
          { id: 6, text: '🎈 Air in balloon' },
          { id: 7, text: '🪵 Wood block' },
          { id: 8, text: '🍯 Honey' },
        ],
        targets: [
          { id: 1, text: '🧊 Solid' },
          { id: 2, text: '💧 Liquid' },
          { id: 3, text: '💨 Gas' },
          { id: 4, text: '🧊 Solid' },
          { id: 5, text: '💧 Liquid' },
          { id: 6, text: '💨 Gas' },
          { id: 7, text: '🧊 Solid' },
          { id: 8, text: '💧 Liquid' },
        ],
      },
    },
    {
      id: 'science-electricity-r2-d3',
      title: 'Electricity Safety ⚡',
      instruction: 'Stay safe around electricity!',
      type: 'multipleChoice',
      difficulty: 3,
      data: [
        { question: 'Should you touch electrical outlets with your fingers? 🔌', options: ['No, never!', 'Yes, it is fun', 'Only when wet', 'Only at night'], answer: 'No, never!', hint: 'Outlets have dangerous electricity inside!' },
        { question: 'What should you NEVER use near water? 💧', options: ['Electrical appliances', 'Towels', 'Soap', 'Rubber ducks'], answer: 'Electrical appliances', hint: 'Water and electricity together are very dangerous!' },
        { question: 'What happens during a power outage? 🕯️', options: ['The electricity stops and lights go out', 'Everything gets louder', 'The house spins', 'Nothing changes'], answer: 'The electricity stops and lights go out', hint: 'No power means no lights or TV!' },
        { question: 'Electricity flows through things called... 🔌', options: ['Wires and circuits', 'Ropes', 'String', 'Paper'], answer: 'Wires and circuits', hint: 'Metal wires carry electricity!' },
        { question: 'What powers a flashlight? 🔦', options: ['Batteries', 'Water', 'Wind', 'Food'], answer: 'Batteries', hint: 'Small cylinders that store energy!' },
        { question: 'Lightning is a form of... ⚡', options: ['Electricity in nature', 'Water', 'Wind', 'Sound'], answer: 'Electricity in nature', hint: 'A huge spark between clouds and the ground!' },
        { question: 'Where should you go during a lightning storm? ⛈️', options: ['Inside a building', 'Under a tall tree', 'In a swimming pool', 'On top of a hill'], answer: 'Inside a building', hint: 'Buildings protect you from lightning!' },
        { question: 'A light switch works by... 💡', options: ['Opening or closing an electrical circuit', 'Making wind', 'Creating water', 'Spinning'], answer: 'Opening or closing an electrical circuit', hint: 'On = closed circuit (electricity flows), Off = open circuit!' },
      ],
    },
    {
      id: 'science-space-exploration-r2-d3',
      title: 'Space Explorers 🚀',
      instruction: 'Learn about exploring outer space!',
      type: 'flashcard',
      difficulty: 3,
      data: [
        { front: '🚀 Rocket', back: 'A powerful vehicle that blasts off into space!' },
        { front: '👨‍🚀 Astronaut', back: 'A person who travels to outer space!' },
        { front: '🛸 Space Station', back: 'A big laboratory floating in space where astronauts live and work!' },
        { front: '🌑 Moon Landing', back: 'In 1969, humans first walked on the Moon!' },
        { front: '🔭 Telescope', back: 'A tool that makes faraway things look close — see stars and planets!' },
        { front: '🛰️ Satellite', back: 'A machine that orbits Earth — helps with TV, GPS, and weather!' },
        { front: '🧑‍🚀 Space Suit', back: 'Special clothes astronauts wear to survive in space — provides air and protection!' },
        { front: '🌌 Galaxy', back: 'A huge group of billions of stars — we live in the Milky Way galaxy!' },
      ],
    },
    {
      id: 'science-animal-adaptations-r2-d3',
      title: 'Animal Superpowers! 🦎',
      instruction: 'How do animals survive in their habitats?',
      type: 'multipleChoice',
      difficulty: 3,
      data: [
        { question: 'A chameleon changes color to... 🦎', options: ['Hide from predators (camouflage)', 'Look pretty', 'Stay warm', 'Find water'], answer: 'Hide from predators (camouflage)', hint: 'Blending in helps them hide!' },
        { question: 'Why do polar bears have thick white fur? 🐻‍❄️', options: ['To stay warm and blend into snow', 'To look fluffy', 'To swim faster', 'To be seen easily'], answer: 'To stay warm and blend into snow', hint: 'White fur in white snow = hidden!' },
        { question: 'A giraffe has a long neck so it can... 🦒', options: ['Reach leaves high in trees', 'Touch the clouds', 'See other countries', 'Run faster'], answer: 'Reach leaves high in trees', hint: 'Tall neck = tall food!' },
        { question: 'Why do birds fly south in winter? 🐦', options: ['To find warmer weather and food', 'For vacation', 'Because they are lost', 'To visit friends'], answer: 'To find warmer weather and food', hint: 'Migration helps them survive cold winters!' },
        { question: 'A porcupine has quills (sharp spines) to... 🦔', options: ['Protect itself from predators', 'Look fancy', 'Dig holes', 'Catch fish'], answer: 'Protect itself from predators', hint: 'Ouch! Predators leave porcupines alone!' },
        { question: 'Fish have gills so they can... 🐠', options: ['Breathe underwater', 'Walk on land', 'Fly', 'Talk'], answer: 'Breathe underwater', hint: 'Gills take oxygen from water!' },
        { question: 'A skunk sprays a stinky smell to... 🦨', options: ['Scare away enemies', 'Attract friends', 'Find food', 'Clean itself'], answer: 'Scare away enemies', hint: 'The terrible smell makes predators run away!' },
        { question: 'What is camouflage? 🌿', options: ['Blending in with surroundings to hide', 'Being very loud', 'Running fast', 'Being very big'], answer: 'Blending in with surroundings to hide', hint: 'Like wearing green in a green forest!' },
      ],
    },
    {
      id: 'science-scientific-method-r2-d3',
      title: 'Be a Scientist! 🔬',
      instruction: 'Learn the steps of doing science!',
      type: 'multipleChoice',
      difficulty: 3,
      data: [
        { question: 'The first step in science is to... 🤔', options: ['Ask a question', 'Find the answer', 'Tell everyone', 'Give up'], answer: 'Ask a question', hint: 'Scientists are curious and ask "why" and "how"!' },
        { question: 'A guess about what will happen is called a... 🧪', options: ['Hypothesis', 'Conclusion', 'Result', 'Problem'], answer: 'Hypothesis', hint: 'It is your best guess before testing!' },
        { question: 'Testing your hypothesis is called an... 🔬', options: ['Experiment', 'Vacation', 'Story', 'Drawing'], answer: 'Experiment', hint: 'You test your idea to see if you are right!' },
        { question: 'After the experiment, you look at your... 📊', options: ['Results (what happened)', 'Shoes', 'Phone', 'Lunch'], answer: 'Results (what happened)', hint: 'What did you find out from your test?' },
        { question: 'A scientist writes down everything they observe. This is called... 📝', options: ['Recording data', 'Doodling', 'Copying homework', 'Guessing'], answer: 'Recording data', hint: 'Data is the information you collect!' },
        { question: 'If your hypothesis was wrong, what do you do? ❌', options: ['Learn from it and try again!', 'Quit science forever', 'Cry', 'Pretend it worked'], answer: 'Learn from it and try again!', hint: 'Being wrong is part of learning in science!' },
        { question: 'Which is a scientific tool for measuring? 📏', options: ['Ruler', 'Paintbrush', 'Pillow', 'Toy car'], answer: 'Ruler', hint: 'It has numbers and helps measure length!' },
        { question: 'Why is it important to repeat experiments? 🔁', options: ['To make sure results are correct', 'Because it is boring', 'To waste time', 'It is not important'], answer: 'To make sure results are correct', hint: 'Repeating helps confirm your findings!' },
      ],
    },