    // --- Social R2 D1 (Age 3) — 10 activities ---
    {
      id: 'social-saying-sorry-r2-d1',
      title: 'Saying Sorry 💛',
      instruction: 'When should we say sorry?',
      type: 'multipleChoice',
      difficulty: 1,
      data: [
        { question: 'You accidentally bump into someone. What do you say? 🤕', options: ['Sorry! Are you okay?', 'Watch where you are going!', 'Nothing', 'Ha ha!'], answer: 'Sorry! Are you okay?', hint: 'Saying sorry shows you care!' },
        { question: 'You broke your friend\'s crayon. What should you do? 🖍️', options: ['Say sorry and help fix it', 'Hide it', 'Blame someone else', 'Walk away'], answer: 'Say sorry and help fix it', hint: 'Owning up to mistakes is brave!' },
        { question: 'Your friend says sorry to you. What do you say back? 🤝', options: ['That\'s okay, I forgive you', 'Go away!', 'I don\'t care', 'Nothing'], answer: 'That\'s okay, I forgive you', hint: 'Forgiving makes both people feel better!' },
        { question: 'Is it okay to make mistakes? 💭', options: ['Yes, everyone makes mistakes!', 'No, never!', 'Only grown-ups make mistakes', 'Mistakes are terrible'], answer: 'Yes, everyone makes mistakes!', hint: 'Mistakes help us learn and grow!' },
        { question: 'You spilled juice on the table. What should you do? 🧃', options: ['Say sorry and help clean it up', 'Run away', 'Cry and do nothing', 'Blame the cup'], answer: 'Say sorry and help clean it up', hint: 'Cleaning up shows responsibility!' },
        { question: 'What makes a good apology? 💗', options: ['Meaning it and trying not to do it again', 'Just saying the word sorry fast', 'Rolling your eyes', 'Laughing while saying sorry'], answer: 'Meaning it and trying not to do it again', hint: 'A real sorry comes from the heart!' },
        { question: 'You said something mean to your sister. What now? 😔', options: ['Apologize and say something kind', 'Keep being mean', 'Pretend it didn\'t happen', 'Tell mom she started it'], answer: 'Apologize and say something kind', hint: 'Kind words can fix hurt feelings!' },
        { question: 'When someone forgives you, how should you feel? 😊', options: ['Thankful and relieved', 'Angry', 'Scared', 'Nothing'], answer: 'Thankful and relieved', hint: 'Forgiveness is a gift that feels good!' },
      ],
    },
    {
      id: 'social-my-feelings-r2-d1',
      title: 'Naming My Feelings 😊',
      instruction: 'What feeling is this?',
      type: 'flashcard',
      difficulty: 1,
      data: [
        { front: '😊 Smiling face', back: 'HAPPY — When something wonderful happens and you feel great!' },
        { front: '😢 Crying face', back: 'SAD — When something makes you feel down or blue.' },
        { front: '😤 Grumpy face', back: 'FRUSTRATED — When something is too hard or not going your way!' },
        { front: '😨 Wide eyes', back: 'SCARED — When something feels frightening or unknown.' },
        { front: '🥱 Yawning face', back: 'TIRED — When your body and mind need rest and sleep.' },
        { front: '🤩 Star eyes', back: 'EXCITED — When you can\'t wait for something amazing to happen!' },
        { front: '😔 Looking down', back: 'DISAPPOINTED — When something didn\'t turn out the way you hoped.' },
        { front: '🥰 Hearts face', back: 'LOVED — When people show you how much they care!' },
      ],
    },
    {
      id: 'social-being-gentle-r2-d1',
      title: 'Being Gentle 🤲',
      instruction: 'How do we treat others gently?',
      type: 'multipleChoice',
      difficulty: 1,
      data: [
        { question: 'How do you pet a cat gently? 🐱', options: ['Soft strokes on its back', 'Pull its tail', 'Squeeze it hard', 'Poke its eyes'], answer: 'Soft strokes on its back', hint: 'Gentle means soft and careful!' },
        { question: 'A baby is sleeping. What should you do? 👶', options: ['Be quiet and tiptoe', 'Yell really loud', 'Clap your hands', 'Jump up and down'], answer: 'Be quiet and tiptoe', hint: 'Babies need quiet to sleep!' },
        { question: 'How do you hold a flower without breaking it? 🌸', options: ['Very gently with soft fingers', 'Squeeze it tight', 'Yank it hard', 'Step on it'], answer: 'Very gently with soft fingers', hint: 'Flowers are delicate — handle with care!' },
        { question: 'Your friend fell down. What is the gentle thing to do? 🤕', options: ['Help them up and ask if they\'re okay', 'Laugh at them', 'Walk away', 'Push them again'], answer: 'Help them up and ask if they\'re okay', hint: 'Being gentle means being caring when someone is hurt!' },
        { question: 'How should you close a door? 🚪', options: ['Slowly and carefully', 'Slam it as hard as you can', 'Kick it shut', 'Leave it open'], answer: 'Slowly and carefully', hint: 'Gentle closing keeps fingers safe!' },
        { question: 'When you hug someone, you should... 🤗', options: ['Hug softly, not too tight', 'Squeeze as hard as possible', 'Push them', 'Never hug anyone'], answer: 'Hug softly, not too tight', hint: 'A gentle hug feels warm and safe!' },
        { question: 'What does "gentle hands" mean? 🤲', options: ['Using soft, careful touches', 'Hitting and grabbing', 'Pushing others', 'Throwing things'], answer: 'Using soft, careful touches', hint: 'Gentle hands are kind hands!' },
        { question: 'How should you turn pages in a book? 📖', options: ['Carefully, one at a time', 'Rip them out', 'Fold them', 'As fast as possible'], answer: 'Carefully, one at a time', hint: 'Gentle page turning keeps books nice!' },
      ],
    },
    {
      id: 'social-waiting-turn-r2-d1',
      title: 'Waiting My Turn ⏳',
      instruction: 'Practice patience and taking turns!',
      type: 'multipleChoice',
      difficulty: 1,
      data: [
        { question: 'There is one swing and two kids. What should they do? 🏗️', options: ['Take turns!', 'Fight over it', 'Both sit on it', 'Break it'], answer: 'Take turns!', hint: 'Taking turns means everyone gets a chance!' },
        { question: 'You want a toy someone else is using. What do you do? 🧸', options: ['Wait until they are done', 'Grab it from them', 'Cry and scream', 'Hit them'], answer: 'Wait until they are done', hint: 'Patience means waiting calmly!' },
        { question: 'In a game, it is not your turn yet. You should... 🎲', options: ['Wait patiently for your turn', 'Go anyway', 'Quit the game', 'Take someone else\'s turn'], answer: 'Wait patiently for your turn', hint: 'Everyone gets a turn when they wait!' },
        { question: 'The teacher asks a question. You should... 🙋', options: ['Raise your hand and wait', 'Shout the answer', 'Talk to your neighbor', 'Ignore the teacher'], answer: 'Raise your hand and wait', hint: 'Raising your hand shows respect!' },
        { question: 'You are waiting in line for the slide. What do you do? 🛝', options: ['Wait calmly for your turn', 'Push to the front', 'Cut in line', 'Leave and cry'], answer: 'Wait calmly for your turn', hint: 'Everyone waits their turn in line!' },
        { question: 'Waiting is hard! What can help? 💭', options: ['Count to 10 or take deep breaths', 'Scream and stomp', 'Hit things', 'Run away'], answer: 'Count to 10 or take deep breaths', hint: 'Calming tricks make waiting easier!' },
        { question: 'When it is finally your turn, how do you feel? 😊', options: ['Happy and proud for waiting!', 'Angry', 'Sad', 'Nothing'], answer: 'Happy and proud for waiting!', hint: 'Patience pays off with a good feeling!' },
        { question: 'Why is taking turns important? 🤝', options: ['So everyone gets a fair chance', 'It is not important', 'Only babies take turns', 'To waste time'], answer: 'So everyone gets a fair chance', hint: 'Fairness means everyone is included!' },
      ],
    },
    {
      id: 'social-my-family-r2-d1',
      title: 'My Family and Me 👨‍👩‍👧‍👦',
      instruction: 'Learn about families!',
      type: 'flashcard',
      difficulty: 1,
      data: [
        { front: '👩 Mom / Mama', back: 'A mother who loves and takes care of you!' },
        { front: '👨 Dad / Papa', back: 'A father who loves and takes care of you!' },
        { front: '👧 Sister', back: 'A girl in your family who shares your parents!' },
        { front: '👦 Brother', back: 'A boy in your family who shares your parents!' },
        { front: '👵 Grandma', back: 'Your mom or dad\'s mother — she spoils you with love!' },
        { front: '👴 Grandpa', back: 'Your mom or dad\'s father — he tells great stories!' },
        { front: '👶 Baby', back: 'The youngest family member who needs lots of care!' },
        { front: '❤️ Family Love', back: 'Families come in all shapes and sizes — what matters is love!' },
      ],
    },
    {
      id: 'social-good-manners-r2-d1',
      title: 'Magic Words ✨',
      instruction: 'What is the polite thing to say?',
      type: 'multipleChoice',
      difficulty: 1,
      data: [
        { question: 'Someone gives you a gift. What do you say? 🎁', options: ['Thank you!', 'I wanted something else', 'Give me more', 'Nothing'], answer: 'Thank you!', hint: 'Thank you shows you are grateful!' },
        { question: 'You want a cookie. How do you ask? 🍪', options: ['May I please have a cookie?', 'Give me a cookie!', 'I want it now!', 'Grab it yourself'], answer: 'May I please have a cookie?', hint: 'Please is a magic word!' },
        { question: 'You bumped into someone. What do you say? 💛', options: ['Excuse me, I\'m sorry!', 'Move!', 'Watch out!', 'Nothing'], answer: 'Excuse me, I\'m sorry!', hint: 'Excuse me and sorry show you care!' },
        { question: 'Someone sneezes. What do you say? 🤧', options: ['Bless you!', 'Eww!', 'Don\'t sneeze!', 'Nothing'], answer: 'Bless you!', hint: 'Bless you is kind to say after a sneeze!' },
        { question: 'You need to walk past someone. What do you say? 🚶', options: ['Excuse me, please', 'Move it!', 'Get out of my way', 'Push them'], answer: 'Excuse me, please', hint: 'Excuse me is polite when you need to get by!' },
        { question: 'At the dinner table, you want more milk. How do you ask? 🥛', options: ['Please pass the milk', 'Give me milk!', 'I need milk now!', 'Reach across the table'], answer: 'Please pass the milk', hint: 'Please makes requests polite!' },
        { question: 'Someone holds the door for you. What do you say? 🚪', options: ['Thank you!', 'Took you long enough', 'Nothing', 'About time'], answer: 'Thank you!', hint: 'Always thank people who help you!' },
        { question: 'What are the three magic words? ✨', options: ['Please, Thank you, Sorry', 'Give me, Now, Mine', 'No, Stop, Go', 'Me, My, I'], answer: 'Please, Thank you, Sorry', hint: 'These words make the world kinder!' },
      ],
    },
    {
      id: 'social-helping-others-r2-d1',
      title: 'I Can Help! 🤝',
      instruction: 'How can you help at home and school?',
      type: 'multipleChoice',
      difficulty: 1,
      data: [
        { question: 'Your friend drops their books. What can you do? 📚', options: ['Help them pick the books up', 'Laugh at them', 'Walk away', 'Step on the books'], answer: 'Help them pick the books up', hint: 'Helping friends is kind!' },
        { question: 'Mom is carrying heavy bags. How can you help? 🛍️', options: ['Carry a light bag for her', 'Watch TV', 'Run away', 'Ask for candy'], answer: 'Carry a light bag for her', hint: 'Even small help makes a big difference!' },
        { question: 'After playing, what should you do with your toys? 🧸', options: ['Put them away', 'Leave them on the floor', 'Throw them', 'Hide them'], answer: 'Put them away', hint: 'Cleaning up is a way to help!' },
        { question: 'You see trash on the ground at the park. What can you do? 🗑️', options: ['Pick it up and put it in the bin', 'Ignore it', 'Add more trash', 'Kick it'], answer: 'Pick it up and put it in the bin', hint: 'Keeping places clean helps everyone!' },
        { question: 'A new kid at school looks lonely. How can you help? 😊', options: ['Ask them to play with you', 'Ignore them', 'Tell them to go away', 'Laugh at them'], answer: 'Ask them to play with you', hint: 'Including others is a wonderful way to help!' },
        { question: 'Your little sibling can\'t reach something. What do you do? 👶', options: ['Help them get it safely', 'Say "too bad"', 'Take it for yourself', 'Laugh'], answer: 'Help them get it safely', hint: 'Big kids can help little kids!' },
        { question: 'Why is helping others important? 💝', options: ['It makes everyone happier', 'It is a waste of time', 'Only grown-ups should help', 'It is not important'], answer: 'It makes everyone happier', hint: 'Helping creates a chain of kindness!' },
        { question: 'How does it feel when someone helps you? 🥰', options: ['Warm and happy', 'Angry', 'Scared', 'Nothing'], answer: 'Warm and happy', hint: 'Being helped feels wonderful!' },
      ],
    },
    {
      id: 'social-emotions-faces-r2-d1',
      title: 'Match the Face! 😊',
      instruction: 'Match each feeling to the right face!',
      type: 'dragDrop',
      difficulty: 1,
      data: {
        items: [
          { id: 1, text: 'Happy' },
          { id: 2, text: 'Sad' },
          { id: 3, text: 'Angry' },
          { id: 4, text: 'Scared' },
          { id: 5, text: 'Surprised' },
          { id: 6, text: 'Tired' },
          { id: 7, text: 'Excited' },
          { id: 8, text: 'Shy' },
        ],
        targets: [
          { id: 1, text: '😊 Smiling' },
          { id: 2, text: '😢 Crying' },
          { id: 3, text: '😠 Frowning' },
          { id: 4, text: '😨 Wide eyes' },
          { id: 5, text: '😲 Open mouth' },
          { id: 6, text: '😴 Sleepy eyes' },
          { id: 7, text: '🤩 Star eyes' },
          { id: 8, text: '🫣 Hiding face' },
        ],
      },
    },
    {
      id: 'social-sharing-caring-r2-d1',
      title: 'Sharing Is Caring 🤲',
      instruction: 'What is the best way to share?',
      type: 'multipleChoice',
      difficulty: 1,
      data: [
        { question: 'You have 4 cookies and your friend has 0. What is kind to do? 🍪', options: ['Share some cookies with your friend', 'Eat them all yourself', 'Hide them', 'Throw them away'], answer: 'Share some cookies with your friend', hint: 'Sharing makes both of you happy!' },
        { question: 'There is one crayon left and two kids want it. What should they do? 🖍️', options: ['Take turns using it', 'Fight over it', 'Break it in half', 'Neither uses it'], answer: 'Take turns using it', hint: 'Taking turns is a great way to share!' },
        { question: 'Your friend wants to play with your toy. You should... 🧸', options: ['Let them play with it for a while', 'Say "it\'s mine, go away"', 'Hide all your toys', 'Break the toy'], answer: 'Let them play with it for a while', hint: 'Sharing toys makes playtime more fun!' },
        { question: 'At snack time, your friend forgot their snack. What can you do? 🍎', options: ['Share some of yours', 'Eat yours slowly in front of them', 'Ignore them', 'Laugh at them'], answer: 'Share some of yours', hint: 'Sharing food is a caring thing to do!' },
        { question: 'How does sharing make you feel? 💛', options: ['Good inside — warm and happy', 'Terrible', 'Angry', 'Nothing'], answer: 'Good inside — warm and happy', hint: 'Sharing creates joy for everyone!' },
        { question: 'Is it okay to NOT want to share something very special? 🧸', options: ['Yes, but explain nicely why', 'No, you must always share everything', 'You should never share', 'Just hide it'], answer: 'Yes, but explain nicely why', hint: 'Some things are extra special — just be kind about it!' },
        { question: 'What is a good sharing phrase? 🗣️', options: ['Would you like to use this?', 'This is ALL mine!', 'Go away!', 'I don\'t like you'], answer: 'Would you like to use this?', hint: 'Offering to share is generous!' },
        { question: 'When someone shares with you, you should say... 😊', options: ['Thank you!', 'Give me more!', 'It\'s not enough', 'Nothing'], answer: 'Thank you!', hint: 'Gratitude shows you appreciate their kindness!' },
      ],
    },
    {
      id: 'social-daily-routines-r2-d1',
      title: 'My Daily Routine 🌅',
      instruction: 'What do we do each day?',
      type: 'multipleChoice',
      difficulty: 1,
      data: [
        { question: 'What do you do first when you wake up? 🌅', options: ['Get out of bed and stretch', 'Eat lunch', 'Go to sleep', 'Play outside'], answer: 'Get out of bed and stretch', hint: 'Morning starts with waking up!' },
        { question: 'Before eating, you should... 🧼', options: ['Wash your hands', 'Play with toys', 'Jump on the bed', 'Watch TV'], answer: 'Wash your hands', hint: 'Clean hands keep germs away!' },
        { question: 'After eating, what do you do with your plate? 🍽️', options: ['Put it in the sink', 'Leave it on the table', 'Throw it away', 'Hide it'], answer: 'Put it in the sink', hint: 'Cleaning up after meals is responsible!' },
        { question: 'What do you do before bed? 🌙', options: ['Brush your teeth and put on pajamas', 'Eat a big meal', 'Go to the playground', 'Start homework'], answer: 'Brush your teeth and put on pajamas', hint: 'A bedtime routine helps you sleep well!' },
        { question: 'When should you brush your teeth? 🪥', options: ['Morning and night', 'Only on Mondays', 'Never', 'Once a month'], answer: 'Morning and night', hint: 'Twice a day keeps teeth healthy!' },
        { question: 'What do you do when it is time to go to school? 🎒', options: ['Get dressed and pack your backpack', 'Stay in bed', 'Play video games', 'Eat candy'], answer: 'Get dressed and pack your backpack', hint: 'Getting ready helps you start the day!' },
        { question: 'Why do we have routines? 📋', options: ['They help us know what to expect', 'They are boring', 'They are only for grown-ups', 'They don\'t matter'], answer: 'They help us know what to expect', hint: 'Routines make the day feel organized and safe!' },
        { question: 'What meal do you eat in the morning? ☀️', options: ['Breakfast', 'Lunch', 'Dinner', 'Dessert'], answer: 'Breakfast', hint: 'The first meal of the day to give you energy!' },
      ],
    },
    // --- Social R2 D2 (Age 4) — 10 activities ---
    {
      id: 'social-making-friends-r2-d2',
      title: 'How to Make Friends 👫',
      instruction: 'What are good ways to make friends?',
      type: 'multipleChoice',
      difficulty: 2,
      data: [
        { question: 'You see a kid playing alone. How can you start a friendship? 🤝', options: ['Say "Hi! Want to play together?"', 'Stare at them silently', 'Walk away', 'Take their toy'], answer: 'Say "Hi! Want to play together?"', hint: 'A friendly greeting opens the door to friendship!' },
        { question: 'A good friend is someone who... 👫', options: ['Is kind and listens to you', 'Always gets their way', 'Takes your things', 'Ignores you'], answer: 'Is kind and listens to you', hint: 'Friends treat each other well!' },
        { question: 'Your friend is sad. What should you do? 😢', options: ['Ask what\'s wrong and listen', 'Tell them to stop crying', 'Ignore them', 'Laugh at them'], answer: 'Ask what\'s wrong and listen', hint: 'Good friends care about each other\'s feelings!' },
        { question: 'You and your friend want to play different games. What do you do? 🎮', options: ['Take turns choosing or find a game you both like', 'Always play your game', 'Stop being friends', 'Get angry'], answer: 'Take turns choosing or find a game you both like', hint: 'Compromise means meeting in the middle!' },
        { question: 'What makes someone a good friend? 💗', options: ['Being honest, kind, and fun', 'Giving you presents', 'Doing whatever you say', 'Being better than everyone'], answer: 'Being honest, kind, and fun', hint: 'Good friendships are built on trust and kindness!' },
        { question: 'Your friend did something you don\'t like. What should you do? 💬', options: ['Tell them calmly how you feel', 'Hit them', 'Never talk to them again', 'Tell everyone about it'], answer: 'Tell them calmly how you feel', hint: 'Communication helps solve problems!' },
        { question: 'Can you have more than one best friend? 👯', options: ['Yes! You can have many good friends', 'No, only one forever', 'Friends are not important', 'You shouldn\'t have friends'], answer: 'Yes! You can have many good friends', hint: 'The more friends, the more fun!' },
        { question: 'What should you do when you meet someone new? 🙋', options: ['Smile and introduce yourself', 'Hide', 'Run away', 'Be mean so they leave'], answer: 'Smile and introduce yourself', hint: 'A smile and your name is a great start!' },
      ],
    },
    {
      id: 'social-feelings-body-r2-d2',
      title: 'Feelings in My Body 🫀',
      instruction: 'Where do you feel emotions?',
      type: 'multipleChoice',
      difficulty: 2,
      data: [
        { question: 'When you are nervous, you might feel butterflies in your... 🦋', options: ['Tummy', 'Feet', 'Elbows', 'Hair'], answer: 'Tummy', hint: 'Your stomach feels fluttery when nervous!' },
        { question: 'When you are angry, your face might turn... 😤', options: ['Red and hot', 'Blue and cold', 'Green', 'Purple'], answer: 'Red and hot', hint: 'Anger can make you feel warm in the face!' },
        { question: 'When you are scared, your heart might... 💓', options: ['Beat really fast', 'Stop beating', 'Beat slower', 'Not change'], answer: 'Beat really fast', hint: 'Fear makes your heart race!' },
        { question: 'When you are happy, you might feel... 😊', options: ['Light and bouncy inside', 'Heavy and slow', 'Cold all over', 'Nothing at all'], answer: 'Light and bouncy inside', hint: 'Joy makes you feel energetic!' },
        { question: 'When you are sad, you might feel... 😢', options: ['A tight feeling in your chest', 'Energy to run', 'Very hungry', 'Itchy'], answer: 'A tight feeling in your chest', hint: 'Sadness can make your chest feel heavy!' },
        { question: 'What can you do when your body feels tense from anger? 💪', options: ['Take deep breaths to relax', 'Hold your breath', 'Punch something', 'Scream louder'], answer: 'Take deep breaths to relax', hint: 'Deep breathing calms your body down!' },
        { question: 'Crying is... 😭', options: ['A normal way your body releases feelings', 'Only for babies', 'Bad and wrong', 'Something to be ashamed of'], answer: 'A normal way your body releases feelings', hint: 'Everyone cries sometimes — it is healthy!' },
        { question: 'When you feel excited, you might want to... 🤩', options: ['Jump up and down', 'Sit perfectly still', 'Go to sleep', 'Hide'], answer: 'Jump up and down', hint: 'Excitement gives you energy to move!' },
      ],
    },
    {
      id: 'social-teamwork-r2-d2',
      title: 'Working as a Team 🏆',
      instruction: 'How do we work together?',
      type: 'multipleChoice',
      difficulty: 2,
      data: [
        { question: 'When building blocks together, teammates should... 🧱', options: ['Listen to each other\'s ideas', 'Only use their own ideas', 'Knock down others\' work', 'Work alone'], answer: 'Listen to each other\'s ideas', hint: 'Good teammates listen and share!' },
        { question: 'Your team is cleaning up. One person does nothing. What should you say? 🧹', options: ['We all need to help — can you do this part?', 'Nothing, just do all the work', 'Tell the teacher right away', 'Do nothing too'], answer: 'We all need to help — can you do this part?', hint: 'Encourage everyone to do their part!' },
        { question: 'What makes a team work well? ⭐', options: ['Everyone helping and communicating', 'One person doing everything', 'Fighting over who is boss', 'Ignoring each other'], answer: 'Everyone helping and communicating', hint: 'Teamwork means working together!' },
        { question: 'Your teammate makes a mistake. What do you do? ❌', options: ['Say "it\'s okay, let\'s try again"', 'Yell at them', 'Kick them off the team', 'Laugh at them'], answer: 'Say "it\'s okay, let\'s try again"', hint: 'Encouragement helps everyone improve!' },
        { question: 'In a group project, everyone should... 📋', options: ['Have a job to do', 'Let one person do it all', 'Argue about everything', 'Do nothing'], answer: 'Have a job to do', hint: 'Dividing work means everyone contributes!' },
        { question: 'Your team won a game! What should you do? 🏆', options: ['Celebrate together and be a good sport', 'Brag and make fun of the losers', 'Say you did it all by yourself', 'Ignore your teammates'], answer: 'Celebrate together and be a good sport', hint: 'Good sportsmanship means being kind win or lose!' },
        { question: 'Your team lost a game. What is the right response? 😞', options: ['Say "good game" and try harder next time', 'Cry and blame your teammates', 'Quit and never play again', 'Get angry and throw things'], answer: 'Say "good game" and try harder next time', hint: 'Losing gracefully shows maturity!' },
        { question: 'What is a good team cheer? 🎉', options: ['Go team! We can do it together!', 'I am the best!', 'You all are terrible', 'I don\'t need anyone'], answer: 'Go team! We can do it together!', hint: 'Cheering together builds team spirit!' },
      ],
    },
    {
      id: 'social-calm-down-r2-d2',
      title: 'Calm Down Strategies 🧘',
      instruction: 'What can you do when feelings are BIG?',
      type: 'flashcard',
      difficulty: 2,
      data: [
        { front: '🫁 Belly Breathing', back: 'Put your hand on your tummy. Breathe in slowly — feel it rise. Breathe out — feel it fall. Do it 5 times!' },
        { front: '🔢 Count to 10', back: 'Slowly count 1, 2, 3... all the way to 10. It gives your brain time to calm down!' },
        { front: '🤗 Squeeze a Stuffie', back: 'Hug a stuffed animal or squeeze a stress ball to release tension!' },
        { front: '🎵 Hum a Song', back: 'Humming your favorite song helps you relax and feel better!' },
        { front: '🌈 Think Happy Thoughts', back: 'Close your eyes and think of your favorite place, person, or memory!' },
        { front: '🚶 Take a Walk', back: 'Moving your body helps get rid of big angry or sad energy!' },
        { front: '🎨 Draw Your Feelings', back: 'Draw a picture of how you feel — art helps you express emotions!' },
        { front: '💬 Talk to Someone', back: 'Tell a grown-up or friend how you feel — talking helps!' },
      ],
    },
    {
      id: 'social-empathy-r2-d2',
      title: 'Walking in Their Shoes 👟',
      instruction: 'How would they feel?',
      type: 'multipleChoice',
      difficulty: 2,
      data: [
        { question: 'A new kid joins your class and doesn\'t know anyone. How do they feel? 😟', options: ['Nervous and lonely', 'Super happy', 'Angry', 'Sleepy'], answer: 'Nervous and lonely', hint: 'Being new can be scary!' },
        { question: 'Your friend\'s pet goldfish died. How do they feel? 🐟', options: ['Very sad', 'Excited', 'Angry', 'Bored'], answer: 'Very sad', hint: 'Losing a pet is heartbreaking!' },
        { question: 'Someone laughed at your friend\'s drawing. How do they feel? 🎨', options: ['Hurt and embarrassed', 'Happy', 'Proud', 'Excited'], answer: 'Hurt and embarrassed', hint: 'Being laughed at does not feel good!' },
        { question: 'Your sister got picked for the team. How does she feel? ⚽', options: ['Proud and happy', 'Sad', 'Angry', 'Scared'], answer: 'Proud and happy', hint: 'Being chosen feels great!' },
        { question: 'Empathy means... 💛', options: ['Understanding how someone else feels', 'Not caring about others', 'Thinking only about yourself', 'Being the smartest'], answer: 'Understanding how someone else feels', hint: 'Putting yourself in someone else\'s shoes!' },
        { question: 'Your friend is crying. Even if you don\'t know why, you should... 😢', options: ['Show you care and offer comfort', 'Tell them to stop crying', 'Walk away', 'Laugh'], answer: 'Show you care and offer comfort', hint: 'You don\'t need to know the reason to be kind!' },
        { question: 'How can you show empathy? 🤗', options: ['Listen, be kind, and show you understand', 'Talk about yourself', 'Ignore their feelings', 'Change the subject'], answer: 'Listen, be kind, and show you understand', hint: 'Listening is the foundation of empathy!' },
        { question: 'Someone trips and everyone laughs. What should you do? 🤕', options: ['Help them up and make sure they are okay', 'Laugh too', 'Walk away', 'Film it'], answer: 'Help them up and make sure they are okay', hint: 'Empathy means helping, not laughing!' },
      ],
    },
    {
      id: 'social-safety-rules-r2-d2',
      title: 'Staying Safe 🛡️',
      instruction: 'What are important safety rules?',
      type: 'multipleChoice',
      difficulty: 2,
      data: [
        { question: 'Before crossing the street, you should... 🚦', options: ['Look both ways and hold an adult\'s hand', 'Run across quickly', 'Close your eyes', 'Cross whenever you want'], answer: 'Look both ways and hold an adult\'s hand', hint: 'Looking both ways keeps you safe from cars!' },
        { question: 'If there is a fire, what should you do? 🔥', options: ['Get out of the building and call for help', 'Hide under the bed', 'Open the windows', 'Try to put it out yourself'], answer: 'Get out of the building and call for help', hint: 'Getting out fast is the safest choice!' },
        { question: 'A stranger offers you candy. What do you do? 🍬', options: ['Say no and tell a trusted adult', 'Take it and eat it', 'Go with them', 'Say thank you'], answer: 'Say no and tell a trusted adult', hint: 'Never take things from strangers!' },
        { question: 'When riding in a car, you should always... 🚗', options: ['Wear your seatbelt', 'Stand up', 'Jump around', 'Open the door'], answer: 'Wear your seatbelt', hint: 'Click it — seatbelts save lives!' },
        { question: 'What is the emergency phone number? 📞', options: ['911', '123', '000', '555'], answer: '911', hint: 'Call 911 for police, fire, or ambulance!' },
        { question: 'When swimming, you should always... 🏊', options: ['Have an adult watching you', 'Swim alone', 'Go to the deep end first', 'Swim at night'], answer: 'Have an adult watching you', hint: 'Never swim without a grown-up nearby!' },
        { question: 'If you get lost in a store, what should you do? 🏪', options: ['Find a worker in a uniform and ask for help', 'Leave the store alone', 'Cry in a corner', 'Talk to any stranger'], answer: 'Find a worker in a uniform and ask for help', hint: 'Store workers can help find your family!' },
        { question: 'Why are safety rules important? 🛡️', options: ['They keep us from getting hurt', 'They are just annoying', 'Only for babies', 'They don\'t matter'], answer: 'They keep us from getting hurt', hint: 'Rules protect us every day!' },
      ],
    },
    {
      id: 'social-emotions-situations-r2-d2',
      title: 'How Would You Feel? 🎭',
      instruction: 'Match the situation to the feeling!',
      type: 'dragDrop',
      difficulty: 2,
      data: {
        items: [
          { id: 1, text: '🎂 It\'s your birthday!' },
          { id: 2, text: '🧸 You lost your toy' },
          { id: 3, text: '👻 A spooky noise at night' },
          { id: 4, text: '🎁 Surprise present' },
          { id: 5, text: '😤 Someone cut in line' },
          { id: 6, text: '🏆 You won a game' },
          { id: 7, text: '👋 Friend moved away' },
          { id: 8, text: '🎢 First time on roller coaster' },
        ],
        targets: [
          { id: 1, text: '🤩 Excited' },
          { id: 2, text: '😢 Sad' },
          { id: 3, text: '😨 Scared' },
          { id: 4, text: '😲 Surprised' },
          { id: 5, text: '😠 Angry' },
          { id: 6, text: '😊 Proud' },
          { id: 7, text: '😢 Sad' },
          { id: 8, text: '😬 Nervous' },
        ],
      },
    },
    {
      id: 'social-being-kind-r2-d2',
      title: 'Acts of Kindness 💕',
      instruction: 'Which is the kind choice?',
      type: 'multipleChoice',
      difficulty: 2,
      data: [
        { question: 'You see someone sitting alone at lunch. The kind thing is to... 🍽️', options: ['Invite them to sit with you', 'Point and whisper about them', 'Ignore them', 'Tell them the table is full'], answer: 'Invite them to sit with you', hint: 'Including others is a wonderful act of kindness!' },
        { question: 'Your neighbor is an older person carrying groceries. You could... 👵', options: ['Offer to help carry a bag', 'Run past them', 'Ignore them', 'Take their food'], answer: 'Offer to help carry a bag', hint: 'Helping elderly neighbors is very kind!' },
        { question: 'Your friend is having a bad day. You can cheer them up by... 💛', options: ['Drawing them a nice picture or saying kind words', 'Telling them to get over it', 'Ignoring them', 'Making fun of them'], answer: 'Drawing them a nice picture or saying kind words', hint: 'Small kind gestures mean a lot!' },
        { question: 'A classmate forgot their pencil. You have an extra one. You should... ✏️', options: ['Offer to share your extra pencil', 'Say "that\'s your problem"', 'Hide your extra pencil', 'Tell the teacher'], answer: 'Offer to share your extra pencil', hint: 'Sharing supplies helps everyone learn!' },
        { question: 'What is a compliment? 💬', options: ['Saying something nice about someone', 'Saying something mean', 'Not talking to anyone', 'Bragging about yourself'], answer: 'Saying something nice about someone', hint: 'Compliments make people smile!' },
        { question: 'Which is a kind compliment? 😊', options: ['I really like your painting!', 'Your painting is ugly', 'I don\'t care about your painting', 'Mine is better'], answer: 'I really like your painting!', hint: 'Praising someone\'s work is kind!' },
        { question: 'Random acts of kindness are... 🌟', options: ['Kind things you do without being asked', 'Things people make you do', 'Not important', 'Only for holidays'], answer: 'Kind things you do without being asked', hint: 'Unexpected kindness brightens everyone\'s day!' },
        { question: 'How does being kind affect others? 💫', options: ['It makes them feel valued and happy', 'It makes no difference', 'It makes them feel worse', 'It only helps you'], answer: 'It makes them feel valued and happy', hint: 'Kindness creates a ripple effect of good feelings!' },
      ],
    },
    {
      id: 'social-good-listener-r2-d2',
      title: 'Being a Good Listener 👂',
      instruction: 'How do we listen well?',
      type: 'multipleChoice',
      difficulty: 2,
      data: [
        { question: 'A good listener looks at the person who is... 👀', options: ['Talking', 'Sleeping', 'Eating', 'Running'], answer: 'Talking', hint: 'Eye contact shows you are paying attention!' },
        { question: 'When someone is talking, you should... 🤫', options: ['Wait quietly until they finish', 'Interrupt with your own story', 'Walk away', 'Talk louder'], answer: 'Wait quietly until they finish', hint: 'Let them finish before you speak!' },
        { question: 'Good listening means keeping your... 🖐️', options: ['Body still and facing the speaker', 'Back turned to them', 'Hands over your ears', 'Eyes closed'], answer: 'Body still and facing the speaker', hint: 'Face the person to show you are listening!' },
        { question: 'After someone tells you something, you can show you listened by... 💬', options: ['Saying back what you heard or asking a question', 'Changing the subject', 'Saying nothing', 'Looking at your phone'], answer: 'Saying back what you heard or asking a question', hint: 'Responding shows you paid attention!' },
        { question: 'Why is listening important? 👂', options: ['It helps you understand and learn', 'It is not important', 'Only teachers need to listen', 'It wastes time'], answer: 'It helps you understand and learn', hint: 'Good listeners learn more!' },
        { question: 'Your friend is telling you about their day. You should NOT... ❌', options: ['Play with your toys while they talk', 'Look at them', 'Nod your head', 'Ask questions'], answer: 'Play with your toys while they talk', hint: 'Distractions show you are not listening!' },
        { question: 'When the teacher gives instructions, good listeners... 📝', options: ['Pay attention so they know what to do', 'Talk to their neighbor', 'Daydream', 'Doodle on paper'], answer: 'Pay attention so they know what to do', hint: 'Listening to instructions helps you succeed!' },
        { question: 'Nodding your head while someone talks means... 😊', options: ['You understand and are paying attention', 'You are falling asleep', 'You disagree', 'You are bored'], answer: 'You understand and are paying attention', hint: 'Nodding is a way to show you are listening!' },
      ],
    },
    {
      id: 'social-community-helpers-r2-d2',
      title: 'Community Helpers 🚒',
      instruction: 'Match the helper to what they do!',
      type: 'dragDrop',
      difficulty: 2,
      data: {
        items: [
          { id: 1, text: '👨‍🚒 Firefighter' },
          { id: 2, text: '👩‍⚕️ Doctor' },
          { id: 3, text: '👮 Police Officer' },
          { id: 4, text: '👩‍🏫 Teacher' },
          { id: 5, text: '📬 Mail Carrier' },
          { id: 6, text: '👨‍🍳 Chef' },
          { id: 7, text: '👩‍🌾 Farmer' },
          { id: 8, text: '🧑‍✈️ Pilot' },
        ],
        targets: [
          { id: 1, text: '🔥 Puts out fires' },
          { id: 2, text: '🏥 Helps sick people' },
          { id: 3, text: '🛡️ Keeps us safe' },
          { id: 4, text: '📚 Helps us learn' },
          { id: 5, text: '✉️ Delivers letters' },
          { id: 6, text: '🍳 Cooks food' },
          { id: 7, text: '🌾 Grows our food' },
          { id: 8, text: '✈️ Flies airplanes' },
        ],
      },
    },
    // --- Social R2 D3 (Age 5) — 10 activities ---
    {
      id: 'social-conflict-resolution-r2-d3',
      title: 'Solving Problems Together 🤝',
      instruction: 'What is the best way to solve a conflict?',
      type: 'multipleChoice',
      difficulty: 3,
      data: [
        { question: 'You and your friend both want to be first in line. What should you do? 🏃', options: ['Talk about it and find a fair solution', 'Push them out of the way', 'Never talk to them again', 'Tell the teacher immediately'], answer: 'Talk about it and find a fair solution', hint: 'Talking it out helps you find a fair answer!' },
        { question: 'What are the steps to solve a problem? 📋', options: ['Stop, think, talk it out, find a solution', 'Fight, yell, cry', 'Run away and hide', 'Blame someone else'], answer: 'Stop, think, talk it out, find a solution', hint: 'Pause before reacting!' },
        { question: 'Your sister took your favorite marker. What is the best response? 🖊️', options: ['Ask her calmly to please give it back', 'Grab it from her hands', 'Scream at her', 'Take something of hers'], answer: 'Ask her calmly to please give it back', hint: 'Calm words work better than grabbing!' },
        { question: 'What does "compromise" mean? 🤝', options: ['Both people give a little to find a fair answer', 'One person gets everything they want', 'Nobody gets anything', 'Fighting until someone wins'], answer: 'Both people give a little to find a fair answer', hint: 'Meet in the middle!' },
        { question: 'Two kids want the same book. A good compromise is... 📚', options: ['One reads it first, then the other', 'Rip it in half', 'Neither can read it', 'The bigger kid gets it'], answer: 'One reads it first, then the other', hint: 'Taking turns is a fair compromise!' },
        { question: 'When should you ask an adult for help with a problem? 👩', options: ['When you\'ve tried but can\'t solve it, or someone might get hurt', 'Never', 'Always, for every tiny problem', 'Only if you are losing'], answer: 'When you\'ve tried but can\'t solve it, or someone might get hurt', hint: 'Try first, then get help if needed!' },
        { question: 'Using "I feel" statements helps because... 💬', options: ['It explains your feelings without blaming', 'It makes you sound tough', 'People will feel sorry for you', 'It makes others angry'], answer: 'It explains your feelings without blaming', hint: '"I feel sad when..." is better than "You always..."!' },
        { question: 'After solving a conflict, you should... ✅', options: ['Move on and keep being friends', 'Bring it up again tomorrow', 'Hold a grudge', 'Tell everyone about it'], answer: 'Move on and keep being friends', hint: 'Once it is solved, let it go!' },
      ],
    },
    {
      id: 'social-self-confidence-r2-d3',
      title: 'Believing in Yourself 💪',
      instruction: 'Build your confidence!',
      type: 'multipleChoice',
      difficulty: 3,
      data: [
        { question: 'You are trying something new and it feels hard. What should you think? 🧗', options: ['I can do hard things!', 'I give up', 'I will never be good at anything', 'Only smart people can do this'], answer: 'I can do hard things!', hint: 'A positive attitude helps you succeed!' },
        { question: '"I can\'t do it" can be changed to... 💭', options: ['"I can\'t do it YET"', '"I will never do it"', '"It\'s impossible"', '"Someone else should do it"'], answer: '"I can\'t do it YET"', hint: 'Adding YET means you are still learning!' },
        { question: 'What is a growth mindset? 🌱', options: ['Believing you can improve with practice', 'Thinking you are already perfect', 'Believing nothing ever changes', 'Only caring about winning'], answer: 'Believing you can improve with practice', hint: 'Your brain grows stronger when you try hard!' },
        { question: 'You made a mistake on your drawing. What should you do? 🎨', options: ['Keep trying — mistakes help you learn', 'Throw it away', 'Cry and give up', 'Never draw again'], answer: 'Keep trying — mistakes help you learn', hint: 'Every artist makes mistakes — that is how they get better!' },
        { question: 'What is something you can say to encourage yourself? 🗣️', options: ['"I am brave and I can try"', '"I am terrible at everything"', '"Everyone is better than me"', '"Why do I even bother"'], answer: '"I am brave and I can try"', hint: 'Positive self-talk builds confidence!' },
        { question: 'Your friend can ride a bike but you can\'t yet. How should you feel? 🚲', options: ['Inspired to keep practicing!', 'Jealous and angry', 'Like giving up forever', 'Like you are a failure'], answer: 'Inspired to keep practicing!', hint: 'Everyone learns at their own pace!' },
        { question: 'Confidence means... 💪', options: ['Believing in yourself and your abilities', 'Thinking you are better than everyone', 'Never making mistakes', 'Being the loudest person'], answer: 'Believing in yourself and your abilities', hint: 'Confidence is quiet inner strength!' },
        { question: 'What happens when you practice something every day? 📈', options: ['You get better and better!', 'Nothing changes', 'You get worse', 'It is a waste of time'], answer: 'You get better and better!', hint: 'Practice makes progress!' },
      ],
    },
    {
      id: 'social-diversity-r2-d3',
      title: 'We Are All Different 🌍',
      instruction: 'Celebrate what makes us unique!',
      type: 'multipleChoice',
      difficulty: 3,
      data: [
        { question: 'People around the world speak different... 🗣️', options: ['Languages', 'Volumes', 'Songs', 'Codes'], answer: 'Languages', hint: 'English, Spanish, Mandarin — so many ways to talk!' },
        { question: 'Why is it good that people are different? 🌈', options: ['We can learn from each other', 'It is not good', 'Everyone should be the same', 'Different is bad'], answer: 'We can learn from each other', hint: 'Differences make the world interesting!' },
        { question: 'If someone looks different from you, you should... 👀', options: ['Treat them with the same kindness and respect', 'Stay away from them', 'Point and stare', 'Make fun of them'], answer: 'Treat them with the same kindness and respect', hint: 'Everyone deserves kindness!' },
        { question: 'Families can be... 👨‍👩‍👧‍👦', options: ['Big, small, and all different — and all are wonderful', 'Only one way', 'All the same', 'Only parents and kids'], answer: 'Big, small, and all different — and all are wonderful', hint: 'Love makes a family!' },
        { question: 'Some people use wheelchairs. They are... ♿', options: ['People who get around differently — just as capable', 'Not able to do anything', 'Scary', 'To be avoided'], answer: 'People who get around differently — just as capable', hint: 'Wheelchairs are tools that help people move!' },
        { question: 'People celebrate different holidays. This is... 🎉', options: ['Wonderful — we can learn about new traditions', 'Wrong', 'Confusing', 'Not interesting'], answer: 'Wonderful — we can learn about new traditions', hint: 'Every culture has beautiful celebrations!' },
        { question: 'What should you do if someone makes fun of a person who is different? 💪', options: ['Stand up for them and say that is not kind', 'Join in', 'Laugh along', 'Ignore it'], answer: 'Stand up for them and say that is not kind', hint: 'Be an upstander for fairness!' },
        { question: 'The word "inclusion" means... 🤗', options: ['Making sure everyone is welcome and included', 'Leaving people out', 'Only being with people like you', 'Ignoring others'], answer: 'Making sure everyone is welcome and included', hint: 'Everyone deserves to belong!' },
      ],
    },
    {
      id: 'social-gratitude-r2-d3',
      title: 'Being Thankful 🙏',
      instruction: 'What are you grateful for?',
      type: 'flashcard',
      difficulty: 3,
      data: [
        { front: '🏠 Home', back: 'Be thankful for a warm, safe place to live and sleep!' },
        { front: '👨‍👩‍👧 Family', back: 'Be thankful for people who love and take care of you!' },
        { front: '🍎 Food', back: 'Be thankful for yummy meals that keep you healthy and strong!' },
        { front: '👫 Friends', back: 'Be thankful for friends who play with you and make you laugh!' },
        { front: '📚 School', back: 'Be thankful for teachers who help you learn new things!' },
        { front: '🌳 Nature', back: 'Be thankful for trees, flowers, animals, and the beautiful outdoors!' },
        { front: '🏥 Health', back: 'Be thankful for a body that lets you run, play, and explore!' },
        { front: '💛 Kindness', back: 'Be thankful for all the kind people in the world!' },
      ],
    },
    {
      id: 'social-responsibility-r2-d3',
      title: 'Being Responsible 📋',
      instruction: 'What does being responsible look like?',
      type: 'multipleChoice',
      difficulty: 3,
      data: [
        { question: 'You promised to feed the class hamster. What should you do? 🐹', options: ['Remember and do it every day', 'Forget about it', 'Let someone else do it', 'Only do it when you feel like it'], answer: 'Remember and do it every day', hint: 'Keeping promises is being responsible!' },
        { question: 'After playing outside, you track mud in the house. What should you do? 🥾', options: ['Clean it up', 'Blame the dog', 'Pretend you didn\'t do it', 'Walk in more mud'], answer: 'Clean it up', hint: 'Taking care of messes you make is responsible!' },
        { question: 'Your homework is due tomorrow. What should you do? 📝', options: ['Do it today so it is ready', 'Wait until the morning', 'Forget about it', 'Copy someone else\'s'], answer: 'Do it today so it is ready', hint: 'Planning ahead is responsible!' },
        { question: 'You borrowed a book from the library. What is your responsibility? 📚', options: ['Take care of it and return it on time', 'Lose it', 'Draw in it', 'Keep it forever'], answer: 'Take care of it and return it on time', hint: 'Borrowed things must be returned in good condition!' },
        { question: 'A responsible person... ⭐', options: ['Does what they say they will do', 'Makes excuses', 'Blames others', 'Avoids hard tasks'], answer: 'Does what they say they will do', hint: 'Being reliable means people can count on you!' },
        { question: 'You accidentally broke a vase. The responsible thing is to... 🏺', options: ['Tell the truth and say sorry', 'Hide the pieces', 'Blame the cat', 'Run away'], answer: 'Tell the truth and say sorry', hint: 'Honesty and owning up to mistakes shows responsibility!' },
        { question: 'Taking care of your belongings means... 🎒', options: ['Keeping them organized and in good condition', 'Losing them all the time', 'Breaking them', 'Never cleaning them'], answer: 'Keeping them organized and in good condition', hint: 'Your things last longer when you take care of them!' },
        { question: 'Why is responsibility important? 🌟', options: ['People trust and rely on responsible people', 'It is not important', 'Only adults need to be responsible', 'It makes life harder'], answer: 'People trust and rely on responsible people', hint: 'Being responsible earns respect!' },
      ],
    },
    {
      id: 'social-dealing-with-change-r2-d3',
      title: 'When Things Change 🔄',
      instruction: 'How do we handle changes in life?',
      type: 'multipleChoice',
      difficulty: 3,
      data: [
        { question: 'Your family is moving to a new house. How might you feel? 🏠', options: ['A mix of nervous and excited — both are okay!', 'Only happy', 'You shouldn\'t feel anything', 'Only angry'], answer: 'A mix of nervous and excited — both are okay!', hint: 'Big changes bring many feelings at once!' },
        { question: 'You are starting at a new school. What can help? 🏫', options: ['Remember you will make new friends with time', 'Refuse to go', 'Be mean to everyone', 'Hide in the bathroom'], answer: 'Remember you will make new friends with time', hint: 'New beginnings lead to new friendships!' },
        { question: 'Your best friend moved away. What can you do? 😢', options: ['Stay in touch and make new friends too', 'Never make another friend', 'Be angry at everyone', 'Forget about them'], answer: 'Stay in touch and make new friends too', hint: 'Old friends stay in your heart while new ones come!' },
        { question: 'Change can be... 🔄', options: ['Hard at first but can lead to good things', 'Always terrible', 'Always easy', 'Not real'], answer: 'Hard at first but can lead to good things', hint: 'Change often brings unexpected good surprises!' },
        { question: 'When something changes, it helps to... 💬', options: ['Talk about your feelings with someone you trust', 'Keep everything bottled up inside', 'Pretend nothing changed', 'Be angry at everyone'], answer: 'Talk about your feelings with someone you trust', hint: 'Sharing feelings makes them easier to handle!' },
        { question: 'You got a new baby sibling. How can you adjust? 👶', options: ['Be patient — everyone is learning the new routine', 'Be jealous and mean', 'Demand all the attention', 'Ignore the baby'], answer: 'Be patient — everyone is learning the new routine', hint: 'New babies change the family routine — it takes time!' },
        { question: 'Your favorite teacher is leaving. What can you do? 👩‍🏫', options: ['Thank them for teaching you and welcome the new teacher', 'Refuse to have a new teacher', 'Be rude to the new teacher', 'Stop going to school'], answer: 'Thank them for teaching you and welcome the new teacher', hint: 'Gratitude for the past and openness to the future!' },
        { question: 'What is one good thing about change? 🌱', options: ['You can grow and learn new things', 'Nothing good about it', 'It just makes everything worse', 'Change is always bad'], answer: 'You can grow and learn new things', hint: 'Growth comes from new experiences!' },
      ],
    },
    {
      id: 'social-honesty-r2-d3',
      title: 'Being Honest 🎯',
      instruction: 'Why is honesty important?',
      type: 'multipleChoice',
      difficulty: 3,
      data: [
        { question: 'You broke a plate but nobody saw. What should you do? 🍽️', options: ['Tell the truth about what happened', 'Blame the pet', 'Hide the pieces', 'Say nothing'], answer: 'Tell the truth about what happened', hint: 'Honest people tell the truth even when it is hard!' },
        { question: 'What is a lie? 🤥', options: ['Saying something you know is not true', 'Telling a joke', 'Keeping a surprise party secret', 'Saying nice things'], answer: 'Saying something you know is not true', hint: 'Lies are not the truth!' },
        { question: 'Why is lying a problem? ❌', options: ['People stop trusting you', 'Nothing bad happens', 'Everyone lies so it is fine', 'Lying is fun'], answer: 'People stop trusting you', hint: 'Trust is hard to rebuild after lies!' },
        { question: 'What does it mean to be trustworthy? 🤝', options: ['People can believe what you say', 'You are very strong', 'You are very fast', 'You have lots of toys'], answer: 'People can believe what you say', hint: 'Trustworthy means worthy of trust!' },
        { question: 'Is it okay to tell a "white lie" to not hurt feelings? 💭', options: ['It is better to be kind AND honest — find gentle truth', 'Always lie to be nice', 'Never be nice', 'Lies are always fine'], answer: 'It is better to be kind AND honest — find gentle truth', hint: 'You can be honest without being mean!' },
        { question: 'You copied your friend\'s work. The honest thing to do is... 📝', options: ['Admit it and do your own work', 'Keep pretending it is yours', 'Copy more', 'Lie to the teacher'], answer: 'Admit it and do your own work', hint: 'Doing your own work is honest and fair!' },
        { question: 'Someone asks if you ate the last cookie and you did. You should say... 🍪', options: ['"Yes, I ate it. Sorry!"', '"No, it wasn\'t me"', '"The dog ate it"', 'Nothing and walk away'], answer: '"Yes, I ate it. Sorry!"', hint: 'Telling the truth shows character!' },
        { question: 'Being honest makes you feel... 💛', options: ['Good and proud of yourself', 'Terrible', 'Weak', 'Silly'], answer: 'Good and proud of yourself', hint: 'Honesty brings peace of mind!' },
      ],
    },
    {
      id: 'social-leadership-r2-d3',
      title: 'Being a Leader 🌟',
      instruction: 'What makes a good leader?',
      type: 'multipleChoice',
      difficulty: 3,
      data: [
        { question: 'A good leader... 🌟', options: ['Listens to everyone and helps the group', 'Bosses everyone around', 'Does everything themselves', 'Only cares about winning'], answer: 'Listens to everyone and helps the group', hint: 'Leaders lift others up!' },
        { question: 'When a leader makes a mistake, they should... 💭', options: ['Admit it and learn from it', 'Blame someone else', 'Pretend it didn\'t happen', 'Quit being a leader'], answer: 'Admit it and learn from it', hint: 'Good leaders own their mistakes!' },
        { question: 'A leader helps the team by... 🤝', options: ['Encouraging everyone to do their best', 'Doing all the work alone', 'Telling everyone they are wrong', 'Making others feel bad'], answer: 'Encouraging everyone to do their best', hint: 'Leaders inspire others!' },
        { question: 'Can anyone be a leader? 🙋', options: ['Yes! Leaders come in all ages and sizes', 'No, only grown-ups', 'No, only tall people', 'No, only boys'], answer: 'Yes! Leaders come in all ages and sizes', hint: 'You can be a leader right now!' },
        { question: 'Leading by example means... 👣', options: ['Doing the right thing so others follow', 'Telling others what to do', 'Being the loudest', 'Going first in every line'], answer: 'Doing the right thing so others follow', hint: 'Actions speak louder than words!' },
        { question: 'A leader sees someone being left out. They... 👀', options: ['Include them and make sure everyone feels welcome', 'Ignore it', 'Join in leaving them out', 'Say "not my problem"'], answer: 'Include them and make sure everyone feels welcome', hint: 'Real leaders stand up for others!' },
        { question: 'What is the difference between a leader and a boss? 🤔', options: ['A leader works WITH the team, a boss just gives orders', 'They are the same thing', 'Leaders are mean', 'Bosses are nicer'], answer: 'A leader works WITH the team, a boss just gives orders', hint: 'Leaders roll up their sleeves and help!' },
        { question: 'How can YOU be a leader today? 💪', options: ['Be kind, helpful, and include others', 'Tell everyone what to do', 'Win every game', 'Be the loudest person'], answer: 'Be kind, helpful, and include others', hint: 'Leadership starts with kindness!' },
      ],
    },
    {
      id: 'social-managing-worries-r2-d3',
      title: 'Managing Worries 😰',
      instruction: 'What to do when you feel worried!',
      type: 'flashcard',
      difficulty: 3,
      data: [
        { front: '😰 What is Worry?', back: 'Worry is when your brain keeps thinking about something that MIGHT go wrong. Everyone worries sometimes!' },
        { front: '🫁 Balloon Breathing', back: 'Pretend you are blowing up a balloon slowly. Breathe in through your nose, out through your mouth. Do it 5 times!' },
        { front: '💭 Thought Bubble', back: 'Imagine putting your worry in a bubble and watching it float away into the sky!' },
        { front: '📝 Worry Journal', back: 'Write or draw your worries on paper. Getting them out of your head helps!' },
        { front: '🤗 Comfort Person', back: 'Talk to someone you trust — a parent, teacher, or friend. Sharing worries makes them smaller!' },
        { front: '🦸 Brave Thoughts', back: 'Replace scary thoughts with brave ones: "I am strong. I can handle this. I have people who love me."' },
        { front: '⭐ Worry Time', back: 'Pick 5 minutes a day to think about worries. The rest of the day, remind yourself: "Not now, I will think about it later!"' },
        { front: '🎵 Happy Song', back: 'Sing or listen to a happy song. Music changes how your brain feels!' },
      ],
    },
    {
      id: 'social-digital-citizenship-r2-d3',
      title: 'Being Kind Online 💻',
      instruction: 'How do we behave on the internet?',
      type: 'multipleChoice',
      difficulty: 3,
      data: [
        { question: 'Being kind online means... 💻', options: ['Treating others the way you want to be treated', 'Saying mean things because nobody can see you', 'Ignoring everyone', 'Sharing everything about yourself'], answer: 'Treating others the way you want to be treated', hint: 'Real people with real feelings are behind screens!' },
        { question: 'Someone sends you a mean message. What should you do? 📱', options: ['Don\'t respond — tell a trusted adult', 'Send a meaner message back', 'Share it with everyone', 'Cry and do nothing'], answer: 'Don\'t respond — tell a trusted adult', hint: 'An adult can help handle mean messages!' },
        { question: 'Should you share your password with friends? 🔒', options: ['No, passwords are private', 'Yes, friends share everything', 'Yes, if they ask nicely', 'Only your best friend'], answer: 'No, passwords are private', hint: 'Passwords protect your accounts!' },
        { question: 'Before posting a photo of someone, you should... 📸', options: ['Ask them if it is okay first', 'Post it without asking', 'Only post funny ones', 'Never post photos'], answer: 'Ask them if it is okay first', hint: 'Respecting privacy means asking permission!' },
        { question: 'What is cyberbullying? 😢', options: ['Being mean to someone online', 'Playing video games', 'Sending funny jokes', 'Using a computer'], answer: 'Being mean to someone online', hint: 'Bullying online is just as hurtful as in person!' },
        { question: 'If you see cyberbullying, you should... 👀', options: ['Tell a trusted adult and support the person being bullied', 'Join in', 'Ignore it', 'Share it with friends'], answer: 'Tell a trusted adult and support the person being bullied', hint: 'Be an upstander, not a bystander!' },
        { question: 'Is it okay to pretend to be someone else online? 🎭', options: ['No, always be yourself', 'Yes, it is funny', 'Only as a joke', 'Everyone does it'], answer: 'No, always be yourself', hint: 'Honesty applies online too!' },
        { question: 'The Golden Rule of the Internet is... ✨', options: ['Think before you post — would you say it in person?', 'Post as much as possible', 'Share everything', 'The internet has no rules'], answer: 'Think before you post — would you say it in person?', hint: 'If you wouldn\'t say it face to face, don\'t type it!' },
      ],
    },