// ===== ROUND 3 EXPANSION =====

// --- Social R3 D1 (Age 3) — 10 activities ---
{
  id: 'social-gentle-touch-r3-d1',
  title: 'Gentle Hands 🤲',
  instruction: 'How do we use gentle touches?',
  type: 'multipleChoice',
  difficulty: 1,
  data: [
    { question: 'How do you touch a tiny ladybug? 🐞', options: ['Very softly with one finger', 'Smash it with your hand', 'Grab it tight', 'Throw it'], answer: 'Very softly with one finger', hint: 'Gentle touches keep little creatures safe!' },
    { question: 'Your baby cousin is sleeping. How do you touch them? 👶', options: ['A soft little pat', 'A big poke', 'Shake them awake', 'Pull their hair'], answer: 'A soft little pat', hint: 'Babies need the softest touches!' },
    { question: 'What does "gentle hands" mean? 🤲', options: ['Touching softly and carefully', 'Hitting and pushing', 'Grabbing things fast', 'Poking really hard'], answer: 'Touching softly and carefully', hint: 'Gentle hands are kind and careful!' },
    { question: 'A friend has a sore arm. How do you touch near it? 🤕', options: ['Very gently or not at all', 'Poke the sore spot', 'Squeeze it', 'Slap it'], answer: 'Very gently or not at all', hint: 'When someone is hurt, be extra careful!' },
    { question: 'How do you hold a baby chick? 🐣', options: ['Cup it softly in both hands', 'Squeeze it in one fist', 'Drop it on the ground', 'Shake it'], answer: 'Cup it softly in both hands', hint: 'Baby animals need gentle care!' },
    { question: 'Your friend does not want a hug. What do you do? 🙅', options: ['Give a wave or high five instead', 'Hug them anyway', 'Get angry', 'Push them'], answer: 'Give a wave or high five instead', hint: 'We respect what others want!' },
    { question: 'When you play with a puppy, you should... 🐶', options: ['Pet it gently', 'Pull its ears', 'Sit on it', 'Throw things at it'], answer: 'Pet it gently', hint: 'Animals love gentle pets!' },
    { question: 'You want to touch your friend\'s painting. What do you do? 🎨', options: ['Ask first and touch carefully', 'Grab it right away', 'Rip it', 'Smudge it'], answer: 'Ask first and touch carefully', hint: 'Always ask before touching other people\'s things!' },
    { question: 'Why are gentle touches important? 💕', options: ['They keep everyone safe and happy', 'They are boring', 'Only for babies', 'They are not important'], answer: 'They keep everyone safe and happy', hint: 'Gentle touches show love and respect!' },
    { question: 'How should you pass a toy to a friend? 🧸', options: ['Hand it to them carefully', 'Throw it at them', 'Drop it on the floor', 'Hold on and not let go'], answer: 'Hand it to them carefully', hint: 'Passing gently is sharing kindly!' },
  ],
},
{
  id: 'social-saying-sorry-right-r3-d1',
  title: 'Saying Sorry the Right Way 💛',
  instruction: 'Learn how to say a real sorry!',
  type: 'flashcard',
  difficulty: 1,
  data: [
    { front: '👀 Step 1: Look at Them', back: 'Look at the person you hurt so they know you mean it!' },
    { front: '🗣️ Step 2: Say "I\'m Sorry"', back: 'Use your words: "I\'m sorry I hurt you."' },
    { front: '💬 Step 3: Say What You Did', back: 'Tell them what happened: "I\'m sorry I knocked over your blocks."' },
    { front: '❤️ Step 4: Mean It!', back: 'A real sorry comes from your heart, not just your mouth!' },
    { front: '🔄 Step 5: Try to Fix It', back: 'Help make it better — rebuild the blocks or get a tissue!' },
    { front: '🚫 Step 6: Try Not to Do It Again', back: 'A good sorry means you will be more careful next time!' },
    { front: '🤗 What Happens After Sorry?', back: 'Usually the other person feels better and you can be friends again!' },
    { front: '😊 Saying Sorry Is Brave!', back: 'It takes courage to admit a mistake. You should be proud!' },
  ],
},
{
  id: 'social-playground-friends-r3-d1',
  title: 'Making Friends at the Playground 🛝',
  instruction: 'How do you make a new friend?',
  type: 'multipleChoice',
  difficulty: 1,
  data: [
    { question: 'You see a kid playing alone at the sandbox. What do you do? 🏖️', options: ['Ask if you can play too', 'Stare at them', 'Ignore them', 'Kick their sand castle'], answer: 'Ask if you can play too', hint: 'A simple question can start a friendship!' },
    { question: 'What is a nice way to say hi to someone new? 👋', options: ['Smile and say "Hi, I\'m [your name]!"', 'Say "You look weird"', 'Don\'t talk to them', 'Push them'], answer: 'Smile and say "Hi, I\'m [your name]!"', hint: 'A smile and your name is a great start!' },
    { question: 'A new kid wants to join your game. What do you say? 🎮', options: ['Sure, come play with us!', 'No, go away', 'We don\'t want you', 'Maybe tomorrow'], answer: 'Sure, come play with us!', hint: 'Including others is kind!' },
    { question: 'What can you share at the playground? 🤝', options: ['Toys, balls, and the space', 'Nothing at all', 'Only your snack', 'Just your frown'], answer: 'Toys, balls, and the space', hint: 'Sharing makes playground time more fun!' },
    { question: 'Your new friend wants to play a different game. What do you do? 🎯', options: ['Try their game too!', 'Say no and walk away', 'Get upset', 'Make them play your game'], answer: 'Try their game too!', hint: 'Friends try new things together!' },
    { question: 'What if someone says "No, I don\'t want to play"? 😕', options: ['Say "Okay!" and find someone else', 'Cry and scream', 'Keep asking 100 times', 'Be mean to them'], answer: 'Say "Okay!" and find someone else', hint: 'It is okay if someone says no!' },
    { question: 'How do you show you are friendly? 😊', options: ['Smile and use kind words', 'Frown and cross your arms', 'Hide behind a tree', 'Yell really loud'], answer: 'Smile and use kind words', hint: 'Friendly faces and words bring people together!' },
    { question: 'When it is time to leave the playground, what do you say? 👋', options: ['Bye! It was fun playing with you!', 'Nothing', 'I never liked playing with you', 'See ya, wouldn\'t wanna be ya'], answer: 'Bye! It was fun playing with you!', hint: 'A kind goodbye makes everyone smile!' },
  ],
},
{
  id: 'social-feelings-thermometer-r3-d1',
  title: 'Feelings Thermometer 🌡️',
  instruction: 'Are these big feelings or small feelings?',
  type: 'dragDrop',
  difficulty: 1,
  data: {
    items: [
      { id: 1, text: '😊 A little bit happy' },
      { id: 2, text: '😭 Very very sad, crying hard' },
      { id: 3, text: '😤 A tiny bit annoyed' },
      { id: 4, text: '🤯 SO excited you could burst!' },
      { id: 5, text: '🙂 Feeling okay' },
      { id: 6, text: '😱 Really really scared' },
      { id: 7, text: '😠 A little bit grumpy' },
      { id: 8, text: '🥳 Super duper thrilled!' },
    ],
    targets: [
      { id: 1, text: '🟢 Small Feeling' },
      { id: 2, text: '🔴 Big Feeling' },
      { id: 3, text: '🟢 Small Feeling' },
      { id: 4, text: '🔴 Big Feeling' },
      { id: 5, text: '🟢 Small Feeling' },
      { id: 6, text: '🔴 Big Feeling' },
      { id: 7, text: '🟢 Small Feeling' },
      { id: 8, text: '🔴 Big Feeling' },
    ],
  },
},
{
  id: 'social-care-belongings-r3-d1',
  title: 'Taking Care of My Things 🎒',
  instruction: 'How do we take care of our stuff?',
  type: 'multipleChoice',
  difficulty: 1,
  data: [
    { question: 'Where do your shoes go when you come inside? 👟', options: ['By the door, neatly together', 'Throw them anywhere', 'Under the couch', 'In the fridge'], answer: 'By the door, neatly together', hint: 'Everything has a special spot!' },
    { question: 'What do you do with your crayons after coloring? 🖍️', options: ['Put them back in the box', 'Leave them on the floor', 'Break them', 'Throw them away'], answer: 'Put them back in the box', hint: 'Putting things away keeps them safe!' },
    { question: 'Your teddy bear fell in a puddle. What do you do? 🧸', options: ['Ask a grown-up to help clean it', 'Leave it in the puddle', 'Stomp on it', 'Throw it in the trash'], answer: 'Ask a grown-up to help clean it', hint: 'We take care of our special things!' },
    { question: 'Why should you zip up your backpack? 🎒', options: ['So nothing falls out', 'It does not matter', 'To make it heavier', 'Just because'], answer: 'So nothing falls out', hint: 'Zipping keeps your things safe inside!' },
    { question: 'You got a new book. How do you keep it nice? 📚', options: ['Turn pages gently and keep it on the shelf', 'Rip the pages', 'Draw all over it', 'Leave it outside in the rain'], answer: 'Turn pages gently and keep it on the shelf', hint: 'Gentle hands keep books looking new!' },
    { question: 'What should you do with toys when you are done? 🧩', options: ['Put them back where they belong', 'Leave them everywhere', 'Hide them under the bed', 'Break them apart'], answer: 'Put them back where they belong', hint: 'Cleaning up is taking care of your things!' },
    { question: 'Your jacket fell on the ground. What do you do? 🧥', options: ['Pick it up and hang it on the hook', 'Step on it', 'Leave it there', 'Kick it under the table'], answer: 'Pick it up and hang it on the hook', hint: 'Hanging things up keeps them clean!' },
    { question: 'Why is it good to take care of your toys? 🌟', options: ['So they last a long time', 'It is not important', 'So nobody else can play with them', 'Just to be bossy'], answer: 'So they last a long time', hint: 'Taking care of things means you can enjoy them longer!' },
  ],
},
{
  id: 'social-listening-ears-r3-d1',
  title: 'Listening Ears 👂',
  instruction: 'What does a good listener do?',
  type: 'dragDrop',
  difficulty: 1,
  data: {
    items: [
      { id: 1, text: '👀 Look at the person talking' },
      { id: 2, text: '🗣️ Talk over them loudly' },
      { id: 3, text: '🤫 Stay quiet while they talk' },
      { id: 4, text: '🏃 Run around the room' },
      { id: 5, text: '🧠 Think about what they say' },
      { id: 6, text: '📱 Play with a toy instead' },
      { id: 7, text: '😊 Nod your head' },
      { id: 8, text: '😴 Pretend to fall asleep' },
    ],
    targets: [
      { id: 1, text: '✅ Good Listening' },
      { id: 2, text: '❌ Not Good Listening' },
      { id: 3, text: '✅ Good Listening' },
      { id: 4, text: '❌ Not Good Listening' },
      { id: 5, text: '✅ Good Listening' },
      { id: 6, text: '❌ Not Good Listening' },
      { id: 7, text: '✅ Good Listening' },
      { id: 8, text: '❌ Not Good Listening' },
    ],
  },
},
{
  id: 'social-personal-space-r3-d1',
  title: 'My Personal Space Bubble 🫧',
  instruction: 'Learn about personal space!',
  type: 'multipleChoice',
  difficulty: 1,
  data: [
    { question: 'What is personal space? 🫧', options: ['The area around your body that is just yours', 'A room in your house', 'Outer space', 'A toy'], answer: 'The area around your body that is just yours', hint: 'Your bubble is the space around you!' },
    { question: 'Someone is standing too close. What do you say? 🙋', options: ['Can you please step back a little?', 'Push them away', 'Scream at them', 'Nothing, just feel bad'], answer: 'Can you please step back a little?', hint: 'Using kind words helps people understand!' },
    { question: 'When should you give someone more space? 🤔', options: ['When they look uncomfortable', 'Never', 'Only outside', 'Only at home'], answer: 'When they look uncomfortable', hint: 'Watch for signs that someone needs more room!' },
    { question: 'Is it okay to hug someone without asking? 🤗', options: ['No, always ask first', 'Yes, always hug everyone', 'Only strangers', 'Only when you are sad'], answer: 'No, always ask first', hint: 'Asking first shows respect!' },
    { question: 'In line at school, you should stand... 🏫', options: ['An arm\'s length behind the next person', 'Right on top of them', 'Far far away', 'Sitting on the ground'], answer: 'An arm\'s length behind the next person', hint: 'An arm\'s length is just right!' },
    { question: 'Your friend says "I need space." What does that mean? 💭', options: ['They want to be alone for a bit', 'They want you to fly to space', 'They are being mean', 'They do not like you'], answer: 'They want to be alone for a bit', hint: 'Sometimes people need time alone and that is okay!' },
    { question: 'Someone keeps poking you. What do you do? 😣', options: ['Say "Please stop, I don\'t like that"', 'Poke them back harder', 'Cry quietly', 'Poke someone else'], answer: 'Say "Please stop, I don\'t like that"', hint: 'Use your words to set boundaries!' },
    { question: 'Why is personal space important? ⭐', options: ['It helps everyone feel safe and comfortable', 'It is not important', 'Only grown-ups need it', 'Just a silly rule'], answer: 'It helps everyone feel safe and comfortable', hint: 'Everyone deserves to feel comfortable!' },
  ],
},
{
  id: 'social-playground-rules-r3-d1',
  title: 'Playground Manners 🏗️',
  instruction: 'What are the playground rules?',
  type: 'flashcard',
  difficulty: 1,
  data: [
    { front: '⏳ Wait Your Turn', back: 'Line up for the slide and swings. Everyone gets a turn!' },
    { front: '🤝 Share the Space', back: 'The playground is for everyone — make room for others!' },
    { front: '🚶 Walk, Don\'t Push', back: 'Keep your hands to yourself and walk, don\'t shove!' },
    { front: '📣 Use Inside Voices Outside Too', back: 'You can be loud playing, but don\'t scream in people\'s ears!' },
    { front: '🛝 Go Down the Slide, Not Up', back: 'Slides are for going down. Climb the ladder to go up!' },
    { front: '🧹 Clean Up After Yourself', back: 'Pick up your trash and toys before you leave!' },
    { front: '🆘 Tell a Grown-Up If Someone Is Hurt', back: 'If someone gets hurt, find an adult to help right away!' },
    { front: '😊 Include Everyone', back: 'If someone is alone, invite them to play!' },
  ],
},
{
  id: 'social-helping-at-home-r3-d1',
  title: 'I Can Help at Home! 🏠',
  instruction: 'Match the chore to where it belongs!',
  type: 'dragDrop',
  difficulty: 1,
  data: {
    items: [
      { id: 1, text: '🍽️ Put plate in the sink' },
      { id: 2, text: '🧸 Pick up toys from floor' },
      { id: 3, text: '🛏️ Pull up the blanket' },
      { id: 4, text: '🐕 Fill the water bowl' },
      { id: 5, text: '🧦 Put dirty socks in hamper' },
      { id: 6, text: '📚 Put books on the shelf' },
      { id: 7, text: '🌱 Water the plant' },
      { id: 8, text: '🗑️ Throw away your wrapper' },
    ],
    targets: [
      { id: 1, text: '🍳 Kitchen Helper' },
      { id: 2, text: '🛋️ Living Room Helper' },
      { id: 3, text: '🛏️ Bedroom Helper' },
      { id: 4, text: '🐾 Pet Helper' },
      { id: 5, text: '👕 Laundry Helper' },
      { id: 6, text: '📖 Tidy-Up Helper' },
      { id: 7, text: '🌿 Garden Helper' },
      { id: 8, text: '♻️ Trash Helper' },
    ],
  },
},
{
  id: 'social-bedtime-routine-r3-d1',
  title: 'My Bedtime Routine 🌙',
  instruction: 'What do we do before bedtime?',
  type: 'flashcard',
  difficulty: 1,
  data: [
    { front: '🛁 Step 1: Bath Time!', back: 'Take a warm bath or shower to get clean and cozy!' },
    { front: '🦷 Step 2: Brush Your Teeth', back: 'Brush your teeth so they stay healthy and strong!' },
    { front: '👕 Step 3: Put on Pajamas', back: 'Change into your comfy pajamas!' },
    { front: '📖 Step 4: Story Time', back: 'Pick a book and read with a grown-up. So fun!' },
    { front: '🤗 Step 5: Hugs and Kisses', back: 'Say goodnight with hugs and kisses to your family!' },
    { front: '🧸 Step 6: Tuck In Your Buddy', back: 'Grab your favorite stuffed animal for snuggles!' },
    { front: '💡 Step 7: Lights Out', back: 'Turn off the light. A nightlight is okay too!' },
    { front: '😴 Step 8: Close Your Eyes', back: 'Think of something happy and drift off to dreamland!' },
  ],
},

// --- Social R3 D2 (Age 4) — 10 activities ---
{
  id: 'social-dealing-with-change-r3-d2',
  title: 'When Things Change 🔄',
  instruction: 'How do we handle changes?',
  type: 'multipleChoice',
  difficulty: 2,
  data: [
    { question: 'Your family is moving to a new house. How might you feel? 🏠', options: ['Excited and a little scared — both are okay!', 'Only happy', 'Only angry', 'Nothing at all'], answer: 'Excited and a little scared — both are okay!', hint: 'Big changes bring many feelings at once!' },
    { question: 'You are getting a new teacher. What can help? 👩‍🏫', options: ['Take a deep breath and give them a chance', 'Refuse to go to school', 'Cry all day', 'Be mean to the new teacher'], answer: 'Take a deep breath and give them a chance', hint: 'New people can become great friends!' },
    { question: 'Your best friend moved away. What can you do? 😢', options: ['Draw them a picture and ask to video call', 'Forget about them', 'Never make friends again', 'Be angry at everyone'], answer: 'Draw them a picture and ask to video call', hint: 'Friends can stay connected even far away!' },
    { question: 'Plans got cancelled because of rain. What should you do? 🌧️', options: ['Find something fun to do inside', 'Scream and cry all day', 'Blame someone', 'Break things'], answer: 'Find something fun to do inside', hint: 'Being flexible means finding new fun!' },
    { question: 'A new baby is coming to your family. How do you feel? 👶', options: ['Many feelings — happy, nervous, and curious', 'I should feel only happy', 'Only jealous', 'Nothing'], answer: 'Many feelings — happy, nervous, and curious', hint: 'All your feelings about the baby are valid!' },
    { question: 'What is a "transition"? 🔄', options: ['When something changes from one thing to another', 'A type of dinosaur', 'A game', 'A snack'], answer: 'When something changes from one thing to another', hint: 'Transitions happen every day!' },
    { question: 'You have to stop playing to eat dinner. What helps? ⏰', options: ['A grown-up giving you a 5-minute warning', 'No warning at all', 'Skipping dinner', 'Ignoring the call'], answer: 'A grown-up giving you a 5-minute warning', hint: 'Warnings help us get ready for changes!' },
    { question: 'Change can be... 🌈', options: ['Hard at first but often leads to good things', 'Always terrible', 'Always easy', 'Something that never happens'], answer: 'Hard at first but often leads to good things', hint: 'Many wonderful things come from changes!' },
    { question: 'What can you bring to a new place to feel safe? 🧸', options: ['A favorite toy or comfort item', 'Nothing — just be brave', 'Your entire bedroom', 'A suit of armor'], answer: 'A favorite toy or comfort item', hint: 'A comfort item can help you feel brave!' },
    { question: 'Your routine changed today. Who can you talk to? 💬', options: ['A parent, teacher, or trusted adult', 'Nobody', 'The cat', 'The TV'], answer: 'A parent, teacher, or trusted adult', hint: 'Talking about feelings always helps!' },
  ],
},
{
  id: 'social-making-compromises-r3-d2',
  title: 'Meeting in the Middle 🤝',
  instruction: 'Learn how to make compromises!',
  type: 'multipleChoice',
  difficulty: 2,
  data: [
    { question: 'You want pizza and your friend wants tacos. What is a compromise? 🍕🌮', options: ['Have pizza today and tacos tomorrow', 'Only eat what you want', 'Don\'t eat at all', 'Argue until someone gives up'], answer: 'Have pizza today and tacos tomorrow', hint: 'A compromise means both people get a turn!' },
    { question: 'What does "compromise" mean? 🤔', options: ['Both people give a little to find a solution', 'One person gets everything', 'Nobody gets anything', 'Fighting until you win'], answer: 'Both people give a little to find a solution', hint: 'Compromise means meeting in the middle!' },
    { question: 'Two friends want to play different games at recess. What can they do? 🎲', options: ['Play one game first, then the other', 'Fight about it', 'Neither plays anything', 'Tell the teacher on each other'], answer: 'Play one game first, then the other', hint: 'Taking turns with games is a great compromise!' },
    { question: 'You and your sibling both want the red cup. What can you do? 🔴', options: ['Take turns — one uses it now, the other next time', 'Grab it and run', 'Break it so nobody gets it', 'Scream louder than them'], answer: 'Take turns — one uses it now, the other next time', hint: 'Taking turns is fair for everyone!' },
    { question: 'Is a compromise always easy? 💭', options: ['No, but it is worth it because both people feel heard', 'Yes, super easy always', 'It is impossible', 'Only grown-ups can do it'], answer: 'No, but it is worth it because both people feel heard', hint: 'Compromising takes practice but gets easier!' },
    { question: 'Your friend wants to draw but you want to build blocks. What is a good idea? 🎨🧱', options: ['Draw together for 10 minutes, then build together', 'Only do what you want', 'Refuse to play together', 'Tell them their idea is bad'], answer: 'Draw together for 10 minutes, then build together', hint: 'Doing both activities makes everyone happy!' },
    { question: 'What words help make a compromise? 🗣️', options: ['"How about we..." or "What if we..."', '"No way!" and "I don\'t care!"', '"You always..." and "You never..."', '"I\'m right and you\'re wrong!"'], answer: '"How about we..." or "What if we..."', hint: 'Suggesting ideas with kind words works best!' },
    { question: 'After a good compromise, how do both people feel? 😊', options: ['Pretty happy because they each got something', 'Angry and upset', 'Like a loser', 'Nothing'], answer: 'Pretty happy because they each got something', hint: 'Good compromises make everyone feel okay!' },
  ],
},
{
  id: 'social-good-leader-r3-d2',
  title: 'Being a Good Leader 🌟',
  instruction: 'What makes someone a good leader?',
  type: 'dragDrop',
  difficulty: 2,
  data: {
    items: [
      { id: 1, text: '👂 Listens to everyone\'s ideas' },
      { id: 2, text: '😤 Bosses people around' },
      { id: 3, text: '🤝 Helps others join in' },
      { id: 4, text: '😈 Only does what they want' },
      { id: 5, text: '💪 Encourages the team' },
      { id: 6, text: '🙄 Makes fun of mistakes' },
      { id: 7, text: '📋 Makes fair rules for everyone' },
      { id: 8, text: '🏃 Quits when things get hard' },
    ],
    targets: [
      { id: 1, text: '⭐ Good Leader' },
      { id: 2, text: '🚫 Not a Good Leader' },
      { id: 3, text: '⭐ Good Leader' },
      { id: 4, text: '🚫 Not a Good Leader' },
      { id: 5, text: '⭐ Good Leader' },
      { id: 6, text: '🚫 Not a Good Leader' },
      { id: 7, text: '⭐ Good Leader' },
      { id: 8, text: '🚫 Not a Good Leader' },
    ],
  },
},
{
  id: 'social-creative-gratitude-r3-d2',
  title: 'Creative Thank-Yous 🎨',
  instruction: 'Fun ways to show you are thankful!',
  type: 'flashcard',
  difficulty: 2,
  data: [
    { front: '🎨 Draw a Thank-You Picture', back: 'Draw something special for the person who helped you!' },
    { front: '🎵 Sing a Thank-You Song', back: 'Make up a silly song about why you are grateful!' },
    { front: '💌 Write a Thank-You Note', back: 'Even a few words or scribbles show you care!' },
    { front: '🤗 Give a Thank-You Hug', back: 'A warm hug says "thank you" without words (ask first)!' },
    { front: '⭐ Make a Gratitude Jar', back: 'Write or draw things you are thankful for on slips of paper!' },
    { front: '🌸 Pick a Flower', back: 'Give someone a flower from outside to say thanks!' },
    { front: '🙏 Say It with Details', back: 'Instead of just "thanks," say what you are thankful FOR!' },
    { front: '🎭 Act It Out', back: 'Do a little skit or dance to show your appreciation!' },
    { front: '👫 Do Something Nice Back', back: 'Help the person who helped you — kindness comes full circle!' },
    { front: '📸 Thankful Photo', back: 'Take a picture together and tell them why they are special!' },
  ],
},
{
  id: 'social-handling-disappointment-r3-d2',
  title: 'When Things Don\'t Go My Way 😔',
  instruction: 'How to handle disappointment!',
  type: 'multipleChoice',
  difficulty: 2,
  data: [
    { question: 'You wanted chocolate ice cream but they only have vanilla. What do you do? 🍦', options: ['Try vanilla — it might be yummy too!', 'Scream and cry', 'Throw the vanilla on the ground', 'Refuse to eat anything ever again'], answer: 'Try vanilla — it might be yummy too!', hint: 'Being flexible can lead to happy surprises!' },
    { question: 'You lost a game. What is a good reaction? 🎮', options: ['Say "Good game!" and try again next time', 'Flip the board over', 'Say the game is stupid', 'Never play again'], answer: 'Say "Good game!" and try again next time', hint: 'Good sportsmanship means handling losing well!' },
    { question: 'What does "disappointment" mean? 💭', options: ['Feeling sad because something didn\'t happen the way you wanted', 'Being happy all the time', 'A type of candy', 'Being angry at everyone'], answer: 'Feeling sad because something didn\'t happen the way you wanted', hint: 'Disappointment is when hopes don\'t match what happens!' },
    { question: 'The park trip got cancelled. What can help you feel better? 🌧️', options: ['Talk about your feelings and find a fun backup plan', 'Hold your breath until you turn blue', 'Slam all the doors', 'Be mean to your family'], answer: 'Talk about your feelings and find a fun backup plan', hint: 'Talking and planning help us feel better!' },
    { question: 'You didn\'t get the part you wanted in the school play. What now? 🎭', options: ['Do your best in the part you got!', 'Refuse to be in the play', 'Be mean to the kid who got your part', 'Tell everyone the play is dumb'], answer: 'Do your best in the part you got!', hint: 'Every part matters and can be fun!' },
    { question: 'When you feel disappointed, it helps to... 🧘', options: ['Take deep breaths and count to 10', 'Hold it all inside forever', 'Yell at the nearest person', 'Break your favorite toy'], answer: 'Take deep breaths and count to 10', hint: 'Deep breaths calm your body and mind!' },
    { question: 'Is it okay to feel disappointed? 🤷', options: ['Yes! All feelings are okay to feel', 'No, you should never be sad', 'Only babies feel disappointed', 'No, just pretend to be happy'], answer: 'Yes! All feelings are okay to feel', hint: 'Every feeling is valid and real!' },
    { question: 'After feeling disappointed, what usually happens? 🌈', options: ['The feeling gets smaller and you find something else to enjoy', 'You feel bad forever', 'Nothing ever gets better', 'You forget who you are'], answer: 'The feeling gets smaller and you find something else to enjoy', hint: 'Feelings come and go like clouds in the sky!' },
  ],
},
{
  id: 'social-upstander-r3-d2',
  title: 'Be an Upstander! 🦸',
  instruction: 'Stand up for others who need help!',
  type: 'multipleChoice',
  difficulty: 2,
  data: [
    { question: 'What is an "upstander"? 🦸', options: ['Someone who helps when they see someone being treated badly', 'Someone who stands on a chair', 'Someone who watches and does nothing', 'Someone who joins in being mean'], answer: 'Someone who helps when they see someone being treated badly', hint: 'Upstanders use their bravery to help!' },
    { question: 'You see someone being left out at recess. What do you do? 🏫', options: ['Invite them to play with you', 'Laugh at them', 'Walk away', 'Pretend you didn\'t see'], answer: 'Invite them to play with you', hint: 'Including someone can change their whole day!' },
    { question: 'A kid is being teased about their lunch. What can you say? 🍱', options: ['"That\'s not nice. Everyone\'s food is different and cool!"', '"Yeah, that is a weird lunch"', 'Nothing', '"I agree, that looks gross"'], answer: '"That\'s not nice. Everyone\'s food is different and cool!"', hint: 'Speaking up for others takes courage!' },
    { question: 'What is the difference between a bystander and an upstander? 🤔', options: ['A bystander watches; an upstander helps', 'They are the same thing', 'A bystander is better', 'An upstander watches; a bystander helps'], answer: 'A bystander watches; an upstander helps', hint: 'Upstanders take action!' },
    { question: 'Someone is saying mean things to your friend. What do you do? 😟', options: ['Stand with your friend and tell an adult', 'Join in saying mean things', 'Leave your friend alone', 'Laugh along'], answer: 'Stand with your friend and tell an adult', hint: 'Standing with a friend shows true loyalty!' },
    { question: 'Is it tattling to tell an adult when someone is being hurt? 📢', options: ['No, telling to keep someone safe is the right thing', 'Yes, never tell anyone', 'Only if it is your friend', 'Maybe'], answer: 'No, telling to keep someone safe is the right thing', hint: 'Telling to help someone is brave, not tattling!' },
    { question: 'A new kid doesn\'t speak your language well. Others are laughing. What do you do? 🌍', options: ['Be their buddy and help them feel welcome', 'Laugh too', 'Ignore the situation', 'Avoid the new kid'], answer: 'Be their buddy and help them feel welcome', hint: 'Being kind to newcomers is being an upstander!' },
    { question: 'Being an upstander makes you feel... 💪', options: ['Proud and brave', 'Embarrassed', 'Weak', 'Silly'], answer: 'Proud and brave', hint: 'Helping others is something to be proud of!' },
  ],
},
{
  id: 'social-group-decisions-r3-d2',
  title: 'Deciding Together 🗳️',
  instruction: 'How does a group make a decision?',
  type: 'flashcard',
  difficulty: 2,
  data: [
    { front: '🗣️ Step 1: Everyone Shares Ideas', back: 'Let each person say what they think. No idea is silly!' },
    { front: '👂 Step 2: Listen Carefully', back: 'Pay attention to all the ideas without interrupting!' },
    { front: '🤔 Step 3: Talk About the Ideas', back: 'Discuss what is good about each idea together!' },
    { front: '🗳️ Step 4: Vote or Agree', back: 'Raise hands or talk until the group finds an answer everyone can live with!' },
    { front: '🤝 Step 5: Support the Decision', back: 'Even if your idea wasn\'t picked, support the group\'s choice!' },
    { front: '😊 Why Voting is Fair', back: 'Voting gives everyone an equal say — one person, one vote!' },
    { front: '💡 What If There\'s a Tie?', back: 'Try a new vote, flip a coin, or find a way to combine both ideas!' },
    { front: '⭐ Practice Makes Better', back: 'The more you decide together, the better your group gets at it!' },
  ],
},
{
  id: 'social-respecting-belongings-r3-d2',
  title: 'That\'s Not Mine! 🚫👜',
  instruction: 'How do we respect others\' things?',
  type: 'multipleChoice',
  difficulty: 2,
  data: [
    { question: 'You see a cool toy in your friend\'s bag. What do you do? 🎒', options: ['Ask "Can I see your toy please?"', 'Grab it out of their bag', 'Take it when they are not looking', 'Tell them you want it'], answer: 'Ask "Can I see your toy please?"', hint: 'Always ask before touching someone else\'s things!' },
    { question: 'Your sister\'s book is on the table. You want to read it. What do you do? 📖', options: ['Ask her first if you can borrow it', 'Just take it', 'Hide it in your room', 'Rip out the pages you like'], answer: 'Ask her first if you can borrow it', hint: 'Borrowing means asking and returning!' },
    { question: 'You accidentally broke your friend\'s crayon. What should you do? 🖍️', options: ['Tell them honestly and offer to share yours', 'Hide it in the trash', 'Blame someone else', 'Say it was already broken'], answer: 'Tell them honestly and offer to share yours', hint: 'Honesty and kindness go together!' },
    { question: 'A classmate says you can\'t use their markers. How do you react? ✏️', options: ['Say "Okay!" and use your own', 'Take them anyway', 'Get mad and pout', 'Tell the teacher they are being mean'], answer: 'Say "Okay!" and use your own', hint: 'People have the right to say no!' },
    { question: 'You borrowed a book from the library. When do you return it? 📚', options: ['On time, before the due date', 'Never, I want to keep it', 'When I feel like it', 'Only if someone asks for it'], answer: 'On time, before the due date', hint: 'Returning on time is being responsible!' },
    { question: 'Why should we take care of borrowed things? 🤔', options: ['So the owner gets them back in good shape', 'We don\'t need to', 'Because we will get in trouble', 'Only if they are expensive'], answer: 'So the owner gets them back in good shape', hint: 'Treating borrowed things well shows respect!' },
    { question: 'You found a toy on the playground. What do you do? 🔍', options: ['Give it to a teacher to find the owner', 'Keep it for yourself', 'Throw it away', 'Leave it in the mud'], answer: 'Give it to a teacher to find the owner', hint: 'Found items belong to someone — help them get it back!' },
    { question: 'Your friend shares their snack with you. What do you do? 🍎', options: ['Say thank you and enjoy it carefully', 'Take the whole thing', 'Say "I don\'t like this" and throw it away', 'Ask for more and more'], answer: 'Say thank you and enjoy it carefully', hint: 'Appreciate what others share with you!' },
  ],
},
{
  id: 'social-building-trust-r3-d2',
  title: 'Building Trust 🏗️❤️',
  instruction: 'What builds trust between people?',
  type: 'dragDrop',
  difficulty: 2,
  data: {
    items: [
      { id: 1, text: '✅ Keeping your promises' },
      { id: 2, text: '🤥 Telling lies' },
      { id: 3, text: '🗣️ Being honest even when it\'s hard' },
      { id: 4, text: '📢 Sharing someone\'s secret' },
      { id: 5, text: '🤝 Being there when someone needs you' },
      { id: 6, text: '👻 Disappearing when things get tough' },
      { id: 7, text: '👂 Listening to your friend\'s feelings' },
      { id: 8, text: '😈 Saying nice things then being mean behind their back' },
    ],
    targets: [
      { id: 1, text: '💚 Builds Trust' },
      { id: 2, text: '💔 Breaks Trust' },
      { id: 3, text: '💚 Builds Trust' },
      { id: 4, text: '💔 Breaks Trust' },
      { id: 5, text: '💚 Builds Trust' },
      { id: 6, text: '💔 Breaks Trust' },
      { id: 7, text: '💚 Builds Trust' },
      { id: 8, text: '💔 Breaks Trust' },
    ],
  },
},
{
  id: 'social-communication-styles-r3-d2',
  title: 'How We Communicate 💬',
  instruction: 'Learn different ways people communicate!',
  type: 'flashcard',
  difficulty: 2,
  data: [
    { front: '🗣️ Talking with Words', back: 'Most people use spoken words to share ideas and feelings!' },
    { front: '🤟 Sign Language', back: 'Some people use their hands to talk! It is a real language!' },
    { front: '😊 Facial Expressions', back: 'Your face shows feelings — smiles, frowns, and surprise!' },
    { front: '🖐️ Gestures', back: 'Waving, pointing, and thumbs up are ways to communicate without words!' },
    { front: '✍️ Writing and Drawing', back: 'You can share ideas by writing words or drawing pictures!' },
    { front: '🫂 Body Language', back: 'How you stand and move shows how you feel — arms crossed means upset!' },
    { front: '🔊 Tone of Voice', back: 'HOW you say something matters just as much as WHAT you say!' },
    { front: '👁️ Eye Contact', back: 'Looking at someone when they talk shows you are listening!' },
    { front: '📱 Pictures and Symbols', back: 'Some people use picture boards or devices to communicate!' },
    { front: '💡 Everyone Communicates Differently', back: 'No matter how someone communicates, their thoughts and feelings matter!' },
  ],
},

// --- Social R3 D3 (Age 5) — 10 activities ---
{
  id: 'social-growth-mindset-r3-d3',
  title: 'I Can\'t Do It... YET! 🌱',
  instruction: 'Learn about growth mindset!',
  type: 'dragDrop',
  difficulty: 3,
  data: {
    items: [
      { id: 1, text: '🌱 "I can\'t do it YET, but I\'m learning!"' },
      { id: 2, text: '🪨 "I\'ll never be good at this."' },
      { id: 3, text: '🌱 "Mistakes help me get better!"' },
      { id: 4, text: '🪨 "I give up, this is too hard."' },
      { id: 5, text: '🌱 "Let me try a different way!"' },
      { id: 6, text: '🪨 "I\'m just not a math person."' },
      { id: 7, text: '🌱 "I love a good challenge!"' },
      { id: 8, text: '🪨 "If it\'s not easy, it\'s not for me."' },
    ],
    targets: [
      { id: 1, text: '🌱 Growth Mindset' },
      { id: 2, text: '🪨 Fixed Mindset' },
      { id: 3, text: '🌱 Growth Mindset' },
      { id: 4, text: '🪨 Fixed Mindset' },
      { id: 5, text: '🌱 Growth Mindset' },
      { id: 6, text: '🪨 Fixed Mindset' },
      { id: 7, text: '🌱 Growth Mindset' },
      { id: 8, text: '🪨 Fixed Mindset' },
    ],
  },
},
{
  id: 'social-stereotypes-r3-d3',
  title: 'Breaking Stereotypes 🚫🏷️',
  instruction: 'Anyone can do anything!',
  type: 'multipleChoice',
  difficulty: 3,
  data: [
    { question: 'Can boys like the color pink? 💗', options: ['Yes! Colors are for everyone', 'No, pink is only for girls', 'Only sometimes', 'Only if nobody is looking'], answer: 'Yes! Colors are for everyone', hint: 'There are no boy colors or girl colors!' },
    { question: 'Can girls be great at sports? ⚽', options: ['Absolutely! Girls can be amazing athletes', 'No, sports are for boys', 'Only some sports', 'Only if boys let them'], answer: 'Absolutely! Girls can be amazing athletes', hint: 'Anyone can be great at any sport!' },
    { question: 'What is a "stereotype"? 🏷️', options: ['An unfair idea about a group of people that isn\'t always true', 'A type of music player', 'A kind of sticker', 'A compliment'], answer: 'An unfair idea about a group of people that isn\'t always true', hint: 'Stereotypes put people in unfair boxes!' },
    { question: 'Can boys like cooking and baking? 🧁', options: ['Yes! Some of the best chefs are boys and men', 'No, that is only for girls', 'Only for special occasions', 'Only if they are grown up'], answer: 'Yes! Some of the best chefs are boys and men', hint: 'Cooking is a skill anyone can enjoy!' },
    { question: 'Can girls like trucks, dinosaurs, and building things? 🦕', options: ['Of course! Interests don\'t depend on being a girl or boy', 'No, those are boy things', 'Maybe, but it is weird', 'Only toy ones'], answer: 'Of course! Interests don\'t depend on being a girl or boy', hint: 'Everyone can like whatever interests them!' },
    { question: 'Someone says "You can\'t do that because you\'re a girl/boy." What do you think? 🤔', options: ['That is a stereotype and it is not true!', 'They must be right', 'I should give up', 'I agree'], answer: 'That is a stereotype and it is not true!', hint: 'Never let a stereotype stop you!' },
    { question: 'Can boys cry when they are sad? 😢', options: ['Yes! Everyone has feelings and it is healthy to express them', 'No, boys should never cry', 'Only in private', 'Only babies cry'], answer: 'Yes! Everyone has feelings and it is healthy to express them', hint: 'Crying is a normal, healthy way to express feelings!' },
    { question: 'Why is it important to challenge stereotypes? 💪', options: ['So everyone feels free to be themselves', 'It is not important', 'To start arguments', 'Because adults say so'], answer: 'So everyone feels free to be themselves', hint: 'Everyone deserves to be who they truly are!' },
    { question: 'Can anyone become a doctor, artist, or scientist? 🔬', options: ['Yes! These jobs are for anyone who works hard', 'Only certain people can', 'Only smart people', 'Only tall people'], answer: 'Yes! These jobs are for anyone who works hard', hint: 'Hard work and passion matter more than anything else!' },
    { question: 'Your friend likes something unusual. What do you do? 🎭', options: ['Support them — being unique is awesome!', 'Make fun of them', 'Tell them to like normal things', 'Stop being their friend'], answer: 'Support them — being unique is awesome!', hint: 'Great friends celebrate what makes each person special!' },
  ],
},
{
  id: 'social-digital-footprint-r3-d3',
  title: 'Your Digital Footprint 👣💻',
  instruction: 'What you do online stays online!',
  type: 'flashcard',
  difficulty: 3,
  data: [
    { front: '👣 What Is a Digital Footprint?', back: 'Everything you do online leaves a trail — like footprints in the sand!' },
    { front: '📸 Photos Online', back: 'Pictures posted online can be seen by many people and are hard to take back!' },
    { front: '💬 Kind Words Online', back: 'Be just as kind online as you are in person. Words stay forever!' },
    { front: '🔒 Private Information', back: 'Never share your name, address, school, or phone number online!' },
    { front: '🤔 Think Before You Post', back: 'Ask yourself: Would I want my teacher or grandma to see this?' },
    { front: '👀 People Are Watching', back: 'Anyone might see what you post — not just your friends!' },
    { front: '⏳ The Internet Never Forgets', back: 'Even if you delete something, copies might still exist somewhere!' },
    { front: '✅ Positive Footprint', back: 'Share kindness, creativity, and helpfulness to leave a GOOD digital footprint!' },
    { front: '🙋 Ask a Grown-Up', back: 'Always check with a parent or guardian before posting or sharing anything online!' },
    { front: '🌟 Your Future Self', back: 'What you share today can affect how people see you in the future!' },
  ],
},
{
  id: 'social-resolving-misunderstandings-r3-d3',
  title: 'Oops, That\'s Not What I Meant! 🔄',
  instruction: 'How to fix misunderstandings!',
  type: 'multipleChoice',
  difficulty: 3,
  data: [
    { question: 'What is a "misunderstanding"? 🤷', options: ['When two people think different things about the same situation', 'A type of game', 'When you don\'t understand math', 'A silly word'], answer: 'When two people think different things about the same situation', hint: 'Misunderstandings happen when messages get mixed up!' },
    { question: 'Your friend thinks you were ignoring them, but you just didn\'t hear them. What do you do? 👂', options: ['Explain that you didn\'t hear and you are sorry', 'Get angry at them', 'Ignore them for real now', 'Say "So what?"'], answer: 'Explain that you didn\'t hear and you are sorry', hint: 'Explaining helps clear things up!' },
    { question: 'You said a joke but your friend thought you were being mean. What now? 😬', options: ['Say "I\'m sorry, I was trying to be funny. I didn\'t mean to hurt you"', 'Tell them they can\'t take a joke', 'Laugh at them more', 'Walk away'], answer: 'Say "I\'m sorry, I was trying to be funny. I didn\'t mean to hurt you"', hint: 'If your joke hurt someone, the kind thing is to apologize!' },
    { question: 'How can you prevent misunderstandings? 🛡️', options: ['Speak clearly and check that people understood you', 'Talk really fast', 'Assume everyone knows what you mean', 'Never talk to anyone'], answer: 'Speak clearly and check that people understood you', hint: 'Clear communication prevents confusion!' },
    { question: 'Two friends both think the other is mad. What should they do? 😤😤', options: ['Sit down and talk about what happened calmly', 'Never speak again', 'Get other friends to take sides', 'Have a yelling match'], answer: 'Sit down and talk about what happened calmly', hint: 'Talking it out is always the best first step!' },
    { question: 'What is a good question to ask during a misunderstanding? ❓', options: ['"What did you mean when you said that?"', '"Why are you so dumb?"', '"Don\'t you understand anything?"', '"Are you trying to annoy me?"'], answer: '"What did you mean when you said that?"', hint: 'Asking questions helps you understand the other person!' },
    { question: 'You read a text from a friend that seems rude. What should you consider? 📱', options: ['Texts can sound different than someone means — ask them about it', 'They definitely hate you', 'Send a rude text back immediately', 'Tell everyone they are mean'], answer: 'Texts can sound different than someone means — ask them about it', hint: 'Written words don\'t show tone of voice!' },
    { question: 'After clearing up a misunderstanding, you should... 🤝', options: ['Move forward and not hold a grudge', 'Bring it up every day', 'Stay mad secretly', 'Keep score of who was wrong'], answer: 'Move forward and not hold a grudge', hint: 'Letting go helps friendships grow stronger!' },
  ],
},
{
  id: 'social-mentoring-younger-kids-r3-d3',
  title: 'Being a Great Big Kid! 🌟',
  instruction: 'How to help younger children!',
  type: 'multipleChoice',
  difficulty: 3,
  data: [
    { question: 'A little kid can\'t reach the water fountain. What do you do? 💧', options: ['Help them or find an adult to help', 'Laugh at them', 'Walk away', 'Push them aside'], answer: 'Help them or find an adult to help', hint: 'Big kids can be amazing helpers!' },
    { question: 'A younger child is scared on the first day of school. What can you say? 🏫', options: ['"I was nervous too! It gets really fun, I promise!"', '"You should be scared!"', '"Stop being a baby"', 'Nothing, it is not your problem'], answer: '"I was nervous too! It gets really fun, I promise!"', hint: 'Sharing your own experience helps others feel brave!' },
    { question: 'What does "mentor" mean? 🤔', options: ['An older or more experienced person who helps and guides someone', 'A type of candy', 'A superhero name', 'Someone who is bossy'], answer: 'An older or more experienced person who helps and guides someone', hint: 'Mentors share what they know to help others grow!' },
    { question: 'A little kid keeps making mistakes while learning to draw. What do you say? ✏️', options: ['"You\'re doing great! Keep practicing!"', '"That looks terrible"', '"Let me just do it for you"', '"You\'ll never be good at this"'], answer: '"You\'re doing great! Keep practicing!"', hint: 'Encouragement helps people keep trying!' },
    { question: 'How should you teach a younger kid something new? 📝', options: ['Be patient, go slowly, and show them step by step', 'Do it super fast and expect them to keep up', 'Get frustrated when they don\'t get it right away', 'Just do it for them'], answer: 'Be patient, go slowly, and show them step by step', hint: 'Patience is the key to being a good teacher!' },
    { question: 'A smaller child wants to play your game but doesn\'t know the rules. What do you do? 🎲', options: ['Teach them the rules kindly and play together', 'Tell them to go away', 'Change all the rules to win easily', 'Ignore them completely'], answer: 'Teach them the rules kindly and play together', hint: 'Teaching someone your game can be really fun!' },
    { question: 'Why is being a mentor important? 💡', options: ['It helps others learn AND helps you become a better person', 'It is not important', 'Only to look good', 'To boss people around'], answer: 'It helps others learn AND helps you become a better person', hint: 'When you teach, you learn too!' },
    { question: 'A younger kid falls down and is crying. What do you do? 🩹', options: ['Help them up, comfort them, and find an adult if needed', 'Keep playing your game', 'Tell them to stop crying', 'Point and laugh'], answer: 'Help them up, comfort them, and find an adult if needed', hint: 'Helping someone who is hurt is one of the kindest things!' },
  ],
},
{
  id: 'social-homelessness-poverty-r3-d3',
  title: 'Understanding Homelessness 🏠❤️',
  instruction: 'Learn about people who don\'t have homes.',
  type: 'flashcard',
  difficulty: 3,
  data: [
    { front: '🏠 What Does Homeless Mean?', back: 'Some people don\'t have a house or apartment to live in. This is called being homeless.' },
    { front: '❤️ It\'s Not Their Fault', back: 'People become homeless for many reasons — losing a job, getting sick, or other hard times. It is NOT because they are bad people.' },
    { front: '👨‍👩‍👧 Families Too', back: 'Whole families, including kids, can become homeless. They need help and kindness.' },
    { front: '🍽️ What Do They Need?', back: 'Homeless people need food, warm clothes, a safe place to sleep, and kindness from others.' },
    { front: '🤝 How Can Kids Help?', back: 'Donate old toys and clothes, help at a food drive, or make care packages with a grown-up!' },
    { front: '🙂 Always Be Kind', back: 'A smile or a kind word costs nothing but can mean everything to someone who is struggling.' },
    { front: '🏡 Shelters Help', back: 'Special buildings called shelters give homeless people a warm, safe place to sleep and eat.' },
    { front: '💪 Everyone Deserves Respect', back: 'No matter where someone lives, every person deserves to be treated with respect and dignity.' },
  ],
},
{
  id: 'social-body-language-r3-d3',
  title: 'Reading Body Language 🕺',
  instruction: 'What is this person\'s body telling you?',
  type: 'dragDrop',
  difficulty: 3,
  data: {
    items: [
      { id: 1, text: '😊 Smiling and leaning forward' },
      { id: 2, text: '😤 Arms crossed, looking away' },
      { id: 3, text: '👋 Waving and bouncing' },
      { id: 4, text: '😰 Biting nails, hunched shoulders' },
      { id: 5, text: '🙄 Rolling eyes, turned away' },
      { id: 6, text: '👍 Thumbs up, nodding' },
      { id: 7, text: '😢 Slumped down, head hanging' },
      { id: 8, text: '🤗 Open arms, big smile' },
    ],
    targets: [
      { id: 1, text: '💚 Interested and Happy' },
      { id: 2, text: '😤 Upset or Angry' },
      { id: 3, text: '🥳 Excited' },
      { id: 4, text: '😟 Nervous or Worried' },
      { id: 5, text: '💔 Annoyed or Bored' },
      { id: 6, text: '✅ Agreeing and Supportive' },
      { id: 7, text: '😢 Sad or Defeated' },
      { id: 8, text: '🤗 Welcoming and Friendly' },
    ],
  },
},
{
  id: 'social-time-management-r3-d3',
  title: 'Managing My Time ⏰',
  instruction: 'Learn to use your time wisely!',
  type: 'multipleChoice',
  difficulty: 3,
  data: [
    { question: 'You have homework and want to play outside. What should you do first? 📝', options: ['Finish homework, then play as a reward', 'Play all day and skip homework', 'Do both at the same time', 'Complain about homework forever'], answer: 'Finish homework, then play as a reward', hint: 'Doing the hard thing first makes play time sweeter!' },
    { question: 'What is "time management"? ⏰', options: ['Planning how to use your time so you can do all the things you need to', 'Having a really big clock', 'Moving super fast all the time', 'Never doing anything'], answer: 'Planning how to use your time so you can do all the things you need to', hint: 'Time management means being smart about your time!' },
    { question: 'A timer says you have 5 minutes to clean up. What do you do? ⏱️', options: ['Start right away and work quickly', 'Wait 4 minutes then panic', 'Ignore the timer', 'Say you need 50 more minutes'], answer: 'Start right away and work quickly', hint: 'Starting right away gives you plenty of time!' },
    { question: 'You keep getting distracted while doing a puzzle. What can help? 🧩', options: ['Find a quiet spot with no distractions', 'Turn on the TV while doing it', 'Give up because it is too hard', 'Start 5 other things instead'], answer: 'Find a quiet spot with no distractions', hint: 'A calm space helps you focus!' },
    { question: 'Is it okay to take breaks? 🧘', options: ['Yes! Short breaks help your brain recharge', 'No, work until you drop', 'Only lazy people take breaks', 'Take a break every 30 seconds'], answer: 'Yes! Short breaks help your brain recharge', hint: 'Your brain works better after a short rest!' },
    { question: 'You have three things to do this afternoon. What helps? 📋', options: ['Make a list and do them one at a time', 'Try to do all three at once', 'Do none of them', 'Wait for someone to tell you what to do'], answer: 'Make a list and do them one at a time', hint: 'Lists help you remember and stay organized!' },
    { question: 'What happens when you rush through everything? 🏃💨', options: ['You might make mistakes and have to redo things', 'Everything turns out perfect', 'You finish faster and better', 'Nothing bad happens'], answer: 'You might make mistakes and have to redo things', hint: 'Taking your time usually saves time in the end!' },
    { question: 'It is almost bedtime but you haven\'t cleaned your room. What do you do? 🛏️', options: ['Quickly pick up the most important things and plan to finish tomorrow', 'Stay up all night cleaning', 'Hide the mess under the bed', 'Cry about it'], answer: 'Quickly pick up the most important things and plan to finish tomorrow', hint: 'Do what you can and make a plan for the rest!' },
    { question: 'A visual schedule shows pictures of your day. Why is it helpful? 🖼️', options: ['It helps you know what comes next so you feel ready', 'It is just for decoration', 'It is only for babies', 'Pictures are boring'], answer: 'It helps you know what comes next so you feel ready', hint: 'Knowing the plan helps you feel calm and prepared!' },
    { question: 'What is one thing you can do tonight to make tomorrow easier? 🌙', options: ['Pick out your clothes and pack your bag the night before', 'Stay up as late as possible', 'Do nothing and hope for the best', 'Sleep with your shoes on'], answer: 'Pick out your clothes and pack your bag the night before', hint: 'A little prep tonight means a smoother morning!' },
  ],
},
{
  id: 'social-healthy-friendships-r3-d3',
  title: 'Healthy vs. Unhealthy Friendships 💚💔',
  instruction: 'What makes a friendship healthy?',
  type: 'dragDrop',
  difficulty: 3,
  data: {
    items: [
      { id: 1, text: '😊 They cheer you on when you do well' },
      { id: 2, text: '😢 They make fun of you in front of others' },
      { id: 3, text: '🤝 They say sorry when they hurt your feelings' },
      { id: 4, text: '😤 They get mad when you play with other kids' },
      { id: 5, text: '💬 They listen when you talk' },
      { id: 6, text: '🤫 They tell your secrets to everyone' },
      { id: 7, text: '🎉 They are happy when good things happen to you' },
      { id: 8, text: '👑 They always have to be the boss or they won\'t play' },
    ],
    targets: [
      { id: 1, text: '💚 Healthy Friendship' },
      { id: 2, text: '💔 Unhealthy Friendship' },
      { id: 3, text: '💚 Healthy Friendship' },
      { id: 4, text: '💔 Unhealthy Friendship' },
      { id: 5, text: '💚 Healthy Friendship' },
      { id: 6, text: '💔 Unhealthy Friendship' },
      { id: 7, text: '💚 Healthy Friendship' },
      { id: 8, text: '💔 Unhealthy Friendship' },
    ],
  },
},
{
  id: 'social-self-reflection-r3-d3',
  title: 'My Reflection Journal 📓',
  instruction: 'Learn to think about your own thoughts and feelings!',
  type: 'flashcard',
  difficulty: 3,
  data: [
    { front: '📓 What Is Self-Reflection?', back: 'Self-reflection means thinking about YOUR thoughts, feelings, and actions — like looking in a mirror for your mind!' },
    { front: '🤔 "What went well today?"', back: 'Think about one thing that made you smile or feel proud today!' },
    { front: '😔 "What was hard today?"', back: 'It is okay to think about tough moments. What could you do differently next time?' },
    { front: '❤️ "Who did I help today?"', back: 'Did you do something kind for someone? Even small things count!' },
    { front: '🌟 "What did I learn today?"', back: 'Every day you learn something new — a fact, a skill, or something about yourself!' },
    { front: '🎯 "What is my goal for tomorrow?"', back: 'Pick one thing you want to do or try tomorrow. Small goals add up!' },
    { front: '😊 "How am I feeling right now?"', back: 'Check in with yourself. Name your feeling. Are you happy, tired, excited, or worried?' },
    { front: '📝 Ways to Reflect', back: 'You can draw a picture, talk to someone, write words, or just sit and think quietly!' },
    { front: '💪 Why Reflect?', back: 'Self-reflection helps you understand yourself better and make good choices!' },
    { front: '🌈 Be Kind to Yourself', back: 'When you reflect, don\'t be too hard on yourself. You are doing your best and that is enough!' },
  ],
},
